const INSIGHTS_DATA = [
  {
    id: 1,
    category: 'Tax Strategy',
    title: 'Income Tax Deadlines Everyone Should Know',
    excerpt: 'From 1099s in January to estimated payments in September, here\'s a plain-English guide to the federal income tax calendar — and what happens if you miss a date.',
    readTime: '5 min read',
    date: 'May 8, 2026',
    featured: true,
    href: 'article.html?id=1',
    body: [
      { type: 'p', text: 'The federal tax calendar isn\'t one deadline — it\'s a series of them, spread across the entire year. Miss one and you\'re looking at interest and penalties that compound daily. Know them in advance and you can plan around them without scrambling.' },
      { type: 'p', text: 'Here\'s a chronological breakdown of the key income tax deadlines, who they apply to, and what the consequences are for missing them.' },
      { type: 'h2', text: 'January 31 — 1099s Due to Recipients and the IRS' },
      { type: 'p', text: 'If your business paid any individual or unincorporated vendor $600 or more during the year, you\'re required to issue a Form 1099-NEC (for nonemployee compensation) by January 31. This deadline applies both to sending copies to the recipients and to filing with the IRS. W-2s for employees are due on the same date.' },
      { type: 'p', text: 'Late or missing 1099s carry penalties ranging from $60 to $310 per form depending on how late they are filed, with higher caps for larger businesses. If the IRS determines the failure was intentional, the minimum penalty jumps to $630 per form with no maximum.' },
      { type: 'callout', text: 'Collect W-9s from every contractor before you pay them — not after. Chasing down tax information in January is far more painful than gathering it upfront.' },
      { type: 'h2', text: 'March 15 — Partnership and S-Corp Returns Due (Extended Deadline: September 15)' },
      { type: 'p', text: 'Pass-through entities — partnerships (Form 1065) and S-Corps (Form 1120-S) — file earlier than individuals. Their original due date is March 15 for calendar-year filers. If more time is needed, an automatic six-month extension is available, pushing the deadline to September 15.' },
      { type: 'p', text: 'These returns matter to the owners because the K-1s they generate flow into individual returns. Filing the partnership or S-Corp return late — even on extension — can delay the individual returns of every partner or shareholder.' },
      { type: 'callout', text: 'An extension gives you more time to file — not more time to pay. Any tax owed at the entity level is still due by March 15.' },
      { type: 'h2', text: 'April 15 — Individual and C-Corp Returns Due (Extended Deadline: October 15)' },
      { type: 'p', text: 'April 15 is the most well-known deadline: the original due date for individual income tax returns (Form 1040) and calendar-year C-Corp returns (Form 1120). A six-month extension is available for both, moving the filing deadline to October 15.' },
      { type: 'p', text: 'The same rule applies here as everywhere else in the tax code: the extension covers filing, not payment. If you owe tax, it must be paid by April 15 to avoid interest and late-payment penalties, regardless of whether you file on time or on extension.' },
      { type: 'h2', text: 'Quarterly Estimated Tax Payments' },
      { type: 'p', text: 'If you\'re a sole proprietor, partner, S-Corp shareholder, or anyone else whose income isn\'t subject to withholding, you\'re generally required to pay estimated taxes four times per year. The federal due dates are:' },
      { type: 'ul', items: [
        'Q1 (January–March income): April 15',
        'Q2 (April–May income): June 15',
        'Q3 (June–August income): September 15',
        'Q4 (September–December income): January 15 of the following year',
      ]},
      { type: 'p', text: 'The IRS requires estimated payments if you expect to owe at least $1,000 in federal tax for the year after subtracting withholding. Pennsylvania mirrors the federal schedule but sets its threshold at $500 in state tax.' },
      { type: 'p', text: 'The safest approach is to pay either 100% of last year\'s tax liability (110% if your prior-year AGI exceeded $150,000) or 90% of the current year\'s actual liability. Most of our clients use the prior-year safe harbor as a baseline and adjust mid-year once they have a clearer picture of income.' },
      { type: 'callout', text: 'Underpaying a single quarter can trigger a penalty even if you\'re current on the others. Each quarter is evaluated independently.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'The tax calendar rewards preparation and punishes procrastination. Getting the key dates on your calendar at the start of the year — and making sure you\'re collecting the right information as you go — is the simplest thing you can do to avoid avoidable penalties. If you\'re unsure where you stand on any of these deadlines, reach out before the date arrives, not after.' },
    ],
  },
  {
    id: 2,
    category: 'Bookkeeping',
    title: 'The Reconciliation Habit That Saves Our Clients Hours Every Month',
    excerpt: 'Most business owners reconcile accounts once a year — right before taxes. Here\'s why doing it monthly changes everything, and a simple system to make it stick.',
    readTime: '4 min read',
    date: 'April 22, 2026',
    featured: false,
    href: 'article.html?id=2',
    body: [
      { type: 'p', text: 'Every January, the same thing happens in our office. Clients arrive for tax prep carrying shoeboxes, bank statements from three different institutions, and a mix of apology and anxiety on their faces. They know the books aren\'t clean. They know the cleanup is going to take time — and money.' },
      { type: 'p', text: 'The fix isn\'t complicated. It\'s monthly reconciliation. And it\'s one of the highest-leverage habits any small business owner can build.' },
      { type: 'h2', text: 'What Reconciliation Actually Means' },
      { type: 'p', text: 'Bank reconciliation is the process of comparing your internal financial records — what\'s in your accounting software or ledger — against your bank and credit card statements. The goal is to confirm that every transaction is recorded, categorized correctly, and that the two sets of numbers match.' },
      { type: 'p', text: 'When they don\'t match, you have an error, a missing entry, or a fraud indicator. All three are problems you want to catch now, not eleven months from now.' },
      { type: 'h2', text: 'Why Annual Reconciliation Is So Painful' },
      { type: 'p', text: 'Annual reconciliation feels like doing twelve months of dishes in a single afternoon. Every transaction needs to be revisited. If your bank statements show a $340 charge from a vendor you can\'t remember, you now have to dig through old emails and invoices to figure out what it was. Your memory of what happened in February is fuzzy in December.' },
      { type: 'p', text: 'Errors compound too. A misclassified transaction in Q1 can distort your P&L for the whole year, which distorts your estimated tax calculations, which means you\'re potentially under- or overpaying taxes — all year long — based on bad data.' },
      { type: 'h2', text: 'What Monthly Reconciliation Looks Like in Practice' },
      { type: 'p', text: 'Done monthly, reconciliation is a 30-to-60-minute task for most small businesses. Here\'s the basic process:' },
      { type: 'ul', items: [
        'Download your bank and credit card statements for the month',
        'Open your accounting software (QuickBooks, Xero, Wave, etc.) and navigate to the reconciliation module',
        'Match every statement transaction to a corresponding entry in your books',
        'Flag and research any transactions that don\'t match',
        'When the ending balances agree, mark the reconciliation complete and save the report',
      ]},
      { type: 'p', text: 'That\'s it. The reason it takes so long at year-end is that you\'re doing this 12 times in a row, against a year\'s worth of fuzzy memory.' },
      { type: 'h2', text: 'The System That Makes It Stick' },
      { type: 'p', text: 'Here\'s what we recommend to clients who\'ve struggled to build the habit:' },
      { type: 'ul', items: [
        'Set a recurring calendar reminder for the 5th of each month (after statements close but before too much time passes)',
        'Treat it like a fixed appointment — 45 minutes, no rescheduling',
        'Keep a running "questions" document for transactions you can\'t immediately identify. Email your bookkeeper with that list at the end of the session rather than rabbit-holing in the moment',
        'If you use a credit card for business, reconcile it separately from the bank account',
      ]},
      { type: 'callout', text: 'The clients who reconcile monthly almost never have surprises at tax time. The ones who don\'t almost always do.' },
      { type: 'h2', text: 'When to Hand It Off' },
      { type: 'p', text: 'If you\'re spending more than 90 minutes on monthly reconciliation, or finding frequent errors you can\'t explain, it\'s time to consider bringing in a bookkeeper. The cost of a monthly reconciliation service is almost always less than the time you\'re spending, and far less than the cost of a tax preparer cleaning up 12 months of errors in January.' },
      { type: 'p', text: 'Monthly reconciliation is one of those tasks that feels optional until it isn\'t. Build the habit now, while the books are manageable. It\'s the single highest-impact change most business owners can make to their financial hygiene.' },
    ],
  },
  {
    id: 3,
    category: 'Cash Flow',
    title: 'Cash Flow vs. Profit: Why You Can Be Profitable and Still Run Out of Money',
    excerpt: 'Your P&L says you\'re doing great. Your bank account says otherwise. This is one of the most common surprises we see with growing businesses — and it\'s entirely preventable.',
    readTime: '6 min read',
    date: 'April 10, 2026',
    featured: false,
    href: 'article.html?id=3',
    body: [
      { type: 'p', text: 'One of the most disorienting moments for a growing business owner is watching the bank account drain while the income statement looks healthy. The P&L says you\'re profitable. The bank account says you can\'t make payroll. What\'s going on?' },
      { type: 'p', text: 'This disconnect between profit and cash is not a sign that something is wrong with your business. It\'s a sign that your business is growing — and that you need to understand two different things at once: profitability and cash flow.' },
      { type: 'h2', text: 'Profit Is Not Cash' },
      { type: 'p', text: 'Profit, as reported on your income statement (P&L), is the difference between your revenue and your expenses in a given period. The problem is that your P&L operates on an accrual basis (or at minimum, a recognition basis) — revenue is recorded when earned, not when the cash actually hits your bank account.' },
      { type: 'p', text: 'If you complete a $50,000 project in December but your client pays in February, your December P&L shows a $50,000 revenue event. Your December bank account shows $0 from that project. Profitable month. Cash-starved month. Both are true at the same time.' },
      { type: 'h2', text: 'The Most Common Cash Flow Killers' },
      { type: 'p', text: 'In our experience working with Western PA small businesses, these are the most frequent culprits behind the profit-cash gap:' },
      { type: 'ul', items: [
        'Slow-paying clients: Net-30 or Net-60 payment terms mean you\'re essentially providing an interest-free loan to your customers',
        'Inventory builds: If you purchase inventory or materials before delivering the finished product, cash is consumed before revenue is recognized',
        'Loan principal payments: Loan payments appear as balance sheet events, not expenses — they reduce your cash but don\'t show up as costs on your P&L',
        'Tax payments: Quarterly estimated tax payments are a cash outflow, but they don\'t reduce reported profit in the period you pay them',
        'Capital expenditures: Buying equipment or making improvements reduces your bank account immediately but is only expensed (depreciated) over years on the P&L',
      ]},
      { type: 'h2', text: 'The Three Financial Statements and Why All Three Matter' },
      { type: 'p', text: 'Most business owners focus exclusively on the P&L. Lenders focus mostly on the balance sheet. But the cash flow statement is often the most important of the three for day-to-day operational decision-making.' },
      { type: 'p', text: 'The cash flow statement reconciles profit to actual cash position by accounting for the timing differences described above. It shows:' },
      { type: 'ul', items: [
        'Operating cash flow: Cash generated by the core business, adjusted for working capital changes',
        'Investing cash flow: Cash used to purchase or sell assets',
        'Financing cash flow: Cash from debt or equity transactions, including loan payments',
      ]},
      { type: 'p', text: 'A business can show strong operating cash flow while being negative overall due to heavy capital investment — that\'s often a healthy growth signal. Or it can show positive investing cash flow (selling assets) while bleeding from operations — a danger sign. The P&L alone can\'t tell you any of that.' },
      { type: 'h2', text: 'Cash Flow Forecasting: The Practical Fix' },
      { type: 'p', text: 'The most powerful tool for managing the profit-cash gap is a rolling cash flow forecast. It doesn\'t need to be complicated:' },
      { type: 'ul', items: [
        'List expected cash inflows by week for the next 8–12 weeks (based on when invoices are actually likely to be paid)',
        'List expected cash outflows by week (payroll, rent, vendor payments, loan payments, taxes)',
        'Track the running cash balance week by week',
      ]},
      { type: 'p', text: 'This simple model will surface cash gaps weeks before they become crises, giving you time to accelerate collections, delay discretionary spending, or draw on a line of credit before you\'re in an emergency.' },
      { type: 'callout', text: 'The goal of a cash flow forecast is not to be perfectly accurate — it\'s to eliminate surprises. Even a rough forecast is vastly better than no forecast.' },
      { type: 'h2', text: 'Quick Wins for Improving Cash Flow' },
      { type: 'ul', items: [
        'Shorten your invoice payment terms from Net-30 to Net-15 or Net-10 (or require deposits on larger projects)',
        'Send invoices immediately upon project completion, not at the end of the month',
        'Offer a small early-payment discount (e.g., 1% if paid within 10 days)',
        'Review subscription and vendor payment dates — cluster them to improve predictability',
        'Establish a business line of credit before you need it (banks are reluctant to lend to businesses in crisis)',
      ]},
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'Profitable businesses fail due to cash flow problems more often than most people realize. Understanding the difference between profit and cash — and actively managing both — is one of the most important financial skills a business owner can develop. If your books are clean and up to date, your accountant can run a cash flow report in minutes. If they\'re not, that\'s the first problem to solve.' },
    ],
  },
  {
    id: 4,
    category: 'Tax Strategy',
    title: 'Home Office Deduction: Who Qualifies and What You Can Actually Claim',
    excerpt: 'Remote workers and home-based business owners in Pennsylvania leave money on the table every year. We break down the IRS rules, the two calculation methods, and common mistakes to avoid.',
    readTime: '7 min read',
    date: 'March 28, 2026',
    featured: false,
    href: 'article.html?id=4',
    body: [
      { type: 'p', text: 'The home office deduction is one of the most misunderstood tax benefits available to self-employed individuals and small business owners. Some people claim it aggressively and get away with it. Others who clearly qualify are afraid to claim it at all. The truth, as usual, is in the details.' },
      { type: 'h2', text: 'The Two Requirements' },
      { type: 'p', text: 'To qualify for the home office deduction, the IRS requires that your workspace meet two tests:' },
      { type: 'ul', items: [
        'Regular and exclusive use: The space must be used regularly for business AND for nothing else. A guest bedroom with a desk in it does not qualify. A dedicated room used only for client meetings and bookkeeping does.',
        'Principal place of business: The home office must be your primary place of business, OR a place where you regularly meet clients or customers.',
      ]},
      { type: 'p', text: 'The "exclusive use" requirement is where most deductions get challenged. If your home office doubles as a playroom, a media room, or a general work-from-home space for your day job, the deduction is on shaky ground.' },
      { type: 'h2', text: 'Who Qualifies (and Who Doesn\'t)' },
      { type: 'callout', text: 'Important: W-2 employees cannot claim the home office deduction under current tax law, regardless of how much they work from home. The Tax Cuts and Jobs Act eliminated miscellaneous itemized deductions — including employee business expenses — through 2025. This provision was extended through 2028 under the 2025 reconciliation legislation.' },
      { type: 'p', text: 'If you are self-employed (sole proprietor, single-member LLC, or partner in a partnership), you may deduct home office expenses on Schedule C or Schedule E. If you\'re an S-Corp shareholder-employee, the deduction works differently — the S-Corp typically reimburses you under an accountable plan, which avoids the self-employment tax complications.' },
      { type: 'h2', text: 'The Two Calculation Methods' },
      { type: 'p', text: 'The IRS offers two methods for calculating the deduction:' },
      { type: 'h2', text: '1. The Simplified Method' },
      { type: 'p', text: 'Multiply the square footage of your home office (up to 300 sq ft) by $5. Maximum deduction: $1,500.' },
      { type: 'p', text: 'This method is easy to calculate and requires minimal recordkeeping. It\'s ideal if your actual home expenses are low or your office is small.' },
      { type: 'h2', text: '2. The Regular Method' },
      { type: 'p', text: 'Determine the percentage of your home used for business (home office square footage ÷ total home square footage). Then apply that percentage to your allowable home expenses:' },
      { type: 'ul', items: [
        'Mortgage interest or rent',
        'Homeowner\'s or renter\'s insurance',
        'Utilities (electricity, gas, internet)',
        'Home repairs and maintenance (proportional share)',
        'Depreciation (for homeowners)',
      ]},
      { type: 'p', text: 'For most business owners with a dedicated home office of any meaningful size, the regular method produces a larger deduction — sometimes significantly larger. However, it requires recordkeeping and a depreciation calculation, and it creates a recapture issue when you sell the home (the depreciation taken is taxed as ordinary income at that time).' },
      { type: 'h2', text: 'Common Mistakes We See' },
      { type: 'ul', items: [
        'Claiming shared space: Using the "office" for any non-business purpose disqualifies the deduction for that space entirely',
        'Forgetting state deductions: Pennsylvania allows a home office deduction for self-employed individuals in addition to the federal deduction',
        'Skipping the deduction out of fear: A legitimate home office, properly documented, is an ordinary and necessary business expense. Not claiming it is leaving real money behind',
        'Ignoring depreciation recapture: If you use the regular method and later sell your home, the depreciation claimed becomes taxable income. This doesn\'t mean you shouldn\'t take the deduction — it means you should plan for it',
      ]},
      { type: 'h2', text: 'Documentation We Recommend' },
      { type: 'p', text: 'If you claim the home office deduction, keep:' },
      { type: 'ul', items: [
        'A floor plan or diagram showing the office\'s location in the home',
        'Square footage measurements of the office and the total home',
        'Photos of the dedicated workspace',
        'Annual totals of all home expenses (mortgage statements, utility bills, insurance premiums)',
      ]},
      { type: 'p', text: 'The IRS doesn\'t require you to submit these records with your return, but they\'re what you\'ll need if the deduction is ever questioned.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'If you run a business from home and use a dedicated space exclusively for that business, you almost certainly qualify for this deduction. The question is which method to use and how to document it properly. Run both methods with your actual numbers before deciding — the difference can easily be $2,000–$5,000 or more for a home-based business with meaningful expenses.' },
    ],
  },
  {
    id: 5,
    category: 'Business Advisory',
    title: 'When Is the Right Time to Switch from DIY Bookkeeping to a CPA?',
    excerpt: 'Not every business needs a CPA on day one. But waiting too long has real costs. We outline the four signs that tell us a client has outgrown their current setup.',
    readTime: '5 min read',
    date: 'March 14, 2026',
    featured: false,
    href: 'article.html?id=5',
    body: [
      { type: 'p', text: 'There\'s a phase in every small business\'s life when spreadsheets and weekend bookkeeping sessions get the job done. Revenue is manageable, expenses are straightforward, and the tax return is basically a Schedule C that you can put together yourself in a long afternoon.' },
      { type: 'p', text: 'Then something changes. A second employee. A major contract. A line of credit. The books get more complex at the same time your time gets more scarce, and suddenly you\'re not sure whether the numbers you\'re looking at are right — or what to do with them even if they are.' },
      { type: 'p', text: 'Here are the four indicators we see most consistently in clients who\'ve outgrown their DIY setup.' },
      { type: 'h2', text: '1. You Hire Your First (or Second) Employee' },
      { type: 'p', text: 'Payroll is a compliance minefield. Federal withholding, Social Security and Medicare taxes, FUTA, Pennsylvania unemployment contributions, and local earned income tax (where applicable) all have different rates, filing schedules, and deposit requirements. Get it wrong, and you\'re looking at trust fund penalties that the IRS collects personally from business owners and officers — they don\'t accept "I didn\'t know" as a defense.' },
      { type: 'p', text: 'The moment you have a W-2 employee, the complexity of your back-office obligations increases dramatically. This is typically when DIY breaks down first.' },
      { type: 'h2', text: '2. Your Tax Return Involves Multiple Forms or Schedules' },
      { type: 'p', text: 'A sole proprietor with a simple business can file Schedule C with confidence. But once you have an S-Corp (Form 1120-S), a partnership interest (Form 1065 / Schedule K-1), rental income (Schedule E), or significant depreciable assets (Form 4562 and depreciation schedules), the return is materially more complex. An error in one schedule ripples through the others.' },
      { type: 'p', text: 'Software like TurboTax can produce a technically "complete" return in these situations. It cannot identify the strategies that would have reduced your liability, catch the elections you didn\'t know to make, or flag the errors introduced by feeding the wrong numbers into the forms.' },
      { type: 'h2', text: '3. Your Books Are More Than 60 Days Behind' },
      { type: 'p', text: 'If you don\'t know your current profit and loss — right now, within a few weeks of real time — you\'re managing your business blind. Most DIY bookkeeping breaks down not because the owner doesn\'t want to do it, but because the operations of the business legitimately don\'t leave time for it.' },
      { type: 'p', text: 'The cost of perpetually out-of-date books isn\'t just the cleanup fee in January. It\'s every pricing decision made without current margin data. Every vendor negotiation made without knowing your cash position. Every loan conversation made without accurate financial statements.' },
      { type: 'h2', text: '4. You\'re Making Decisions That Have Permanent Tax Consequences' },
      { type: 'p', text: 'Certain business decisions — entity type election, retirement plan selection, major equipment purchases, selling a business or real estate, bringing on a partner — have tax implications that play out over years or decades. Making these decisions without professional guidance isn\'t just risky for the current year\'s return. It can lock you into a suboptimal structure for years.' },
      { type: 'callout', text: 'The most expensive CPA conversations we have are the ones that start with "I already did X, what should I do now?" There\'s only so much we can fix after the fact.' },
      { type: 'h2', text: 'What "Getting a CPA" Actually Means' },
      { type: 'p', text: 'Working with a CPA doesn\'t necessarily mean handing off everything. Many of our clients do their own day-to-day bookkeeping in QuickBooks and engage us for quarterly reviews, tax planning, and preparation. That arrangement captures most of the value of professional oversight without the full cost of outsourced bookkeeping.' },
      { type: 'p', text: 'Others prefer to hand off the books entirely and focus on running the business. Either approach can work — the key is knowing what your books actually say, what they mean, and what you should be doing differently.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'There\'s no universal answer to when the switch should happen. But if you recognize yourself in two or more of the situations above, the cost of doing it wrong is almost certainly higher than the cost of doing it right. A single missed payroll tax deposit, a missed deduction, or a suboptimal entity structure can cost multiples of what a year of professional service would have cost.' },
    ],
  },
  {
    id: 6,
    category: 'Bookkeeping',
    title: 'Understanding the Chart of Accounts: The Foundation of Clean Books',
    excerpt: 'A poorly structured chart of accounts creates years of pain at tax time. Here\'s how we set one up for our clients — and what categories most small businesses overlook entirely.',
    readTime: '6 min read',
    date: 'February 27, 2026',
    featured: false,
    href: 'article.html?id=6',
    body: [
      { type: 'p', text: 'The chart of accounts is the skeleton of your bookkeeping system. Everything your accountant does — reconciliation, reporting, tax prep — depends on it being structured correctly. Set it up well once, and your books practically organize themselves. Set it up poorly, and you spend every year in cleanup mode.' },
      { type: 'p', text: 'Here\'s how we think about chart of accounts structure for the small businesses we serve, and the categories most owners overlook entirely.' },
      { type: 'h2', text: 'What the Chart of Accounts Actually Is' },
      { type: 'p', text: 'Your chart of accounts (COA) is a complete list of every financial category — every account — that your business uses to record transactions. Think of it as the filing system that determines where every dollar gets sorted. When you pay rent, which account does it go to? When a customer pays an invoice, which account receives it? The COA provides the answers.' },
      { type: 'p', text: 'Accounts fall into five master categories:' },
      { type: 'ul', items: [
        'Assets: What your business owns (cash, receivables, equipment, inventory)',
        'Liabilities: What your business owes (loans, credit card balances, unpaid vendor invoices)',
        'Equity: The owner\'s residual interest in the business (retained earnings, owner draws)',
        'Income/Revenue: Money earned from your business activities',
        'Expenses: Money spent to generate that income',
      ]},
      { type: 'h2', text: 'The Most Common Structural Mistakes' },
      { type: 'p', text: 'The #1 mistake we see is an expenses section that\'s either too granular or not granular enough. Too many accounts (a separate line for every possible expense) creates a P&L that\'s impossible to read at a glance. Too few (everything lumped into "General Expense") makes it impossible to identify where money is actually going.' },
      { type: 'p', text: 'A good expense structure for most small businesses looks something like this:' },
      { type: 'ul', items: [
        'Cost of Goods Sold / Cost of Services (direct costs tied to revenue generation)',
        'Payroll & Benefits (wages, payroll taxes, health insurance)',
        'Occupancy (rent, utilities, janitorial)',
        'Professional Fees (accounting, legal, consulting)',
        'Marketing & Advertising',
        'Technology & Software',
        'Insurance',
        'Vehicle & Travel',
        'Meals & Entertainment (kept separate because the deduction is limited to 50%)',
        'Office Supplies & Miscellaneous',
      ]},
      { type: 'h2', text: 'Accounts Most Small Businesses Overlook' },
      { type: 'p', text: 'Beyond the obvious operating expenses, there are several account types that small businesses frequently miss — often with real financial or tax consequences:' },
      { type: 'ul', items: [
        'Owner\'s Draw / Distribution account: If you\'re a sole proprietor or S-Corp shareholder, how you take money out of the business matters. Distributions should be tracked separately from salary and from business expenses',
        'Due to/from Owner: When owners pay business expenses from personal accounts (or vice versa), there should be a clearing account to track these intercompany transactions',
        'Depreciation expense: If you own equipment, vehicles, or property, depreciation is a real expense that should be recorded monthly — not only at tax time',
        'Unearned Revenue / Customer Deposits: If clients pay you before you deliver services, that money is a liability until earned — not income',
        'Sales Tax Payable: If you collect sales tax, it needs a dedicated liability account so you know exactly what you owe the state at any point',
      ]},
      { type: 'h2', text: 'How to Set It Up in QuickBooks or Xero' },
      { type: 'p', text: 'Both QuickBooks Online and Xero create a default chart of accounts during setup. The default is a reasonable starting point, but it should always be reviewed and adjusted for your specific business. Key customizations:' },
      { type: 'ul', items: [
        'Delete accounts you will never use (simplicity matters)',
        'Add sub-accounts where you need more detail (e.g., breaking "Payroll" into "Wages" and "Payroll Taxes")',
        'Map your expense accounts to the IRS Schedule C categories relevant to your business — your software may have a built-in mapping field',
        'Use account numbers to maintain logical ordering (1000s for assets, 2000s for liabilities, 3000s for equity, 4000s for income, 5000s+ for expenses)',
      ]},
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'A few hours invested in setting up your COA correctly saves dozens of hours at year-end. If you\'ve been in business for more than a year and haven\'t reviewed your chart of accounts against your actual expense patterns, now is a good time. We regularly do COA audits as part of our bookkeeping setup service — if your books feel chaotic, this is almost always the root cause.' },
    ],
  },
  {
    id: 7,
    category: 'Business Advisory',
    title: 'S-Corp Election: Is It the Right Move for Your Business in 2026?',
    excerpt: 'S-Corp status can save a profitable business thousands in self-employment taxes — but it comes with real administrative costs. We walk through the math and who it actually makes sense for.',
    readTime: '8 min read',
    date: 'February 12, 2026',
    featured: false,
    href: 'article.html?id=7',
    body: [
      { type: 'p', text: 'Every year, we have dozens of conversations with business owners who\'ve heard that electing S-Corp status will save them significant money in taxes. Sometimes it\'s true. Sometimes the savings are real but smaller than expected. And sometimes the administrative overhead negates most of the benefit.' },
      { type: 'p', text: 'Here\'s a straightforward framework for evaluating whether an S-Corp election makes sense for your business in 2026.' },
      { type: 'h2', text: 'The Tax Advantage in Plain Language' },
      { type: 'p', text: 'By default, a sole proprietor or single-member LLC owner pays self-employment (SE) tax — currently 15.3% — on all net business income, up to the Social Security wage base ($176,100 in 2026) and 2.9% above that.' },
      { type: 'p', text: 'An S-Corp changes the structure. As an S-Corp shareholder-employee, you pay yourself a "reasonable salary." That salary is subject to payroll taxes (FICA), which mirror SE tax at 15.3%. But any remaining profit distributed to you as a shareholder is not subject to SE tax or FICA. That\'s the savings opportunity.' },
      { type: 'p', text: 'Example: If your business nets $200,000 and you elect S-Corp status, paying yourself a $100,000 salary and taking $100,000 in distributions, you pay FICA on the $100,000 salary but avoid SE tax on the $100,000 distribution. SE tax savings on the distribution: roughly $14,130.' },
      { type: 'h2', text: 'The Costs That Offset the Savings' },
      { type: 'p', text: 'An S-Corp election introduces real, recurring costs that a sole proprietorship or single-member LLC does not have:' },
      { type: 'ul', items: [
        'Payroll processing: You must run payroll and pay yourself a W-2 salary. Payroll service costs typically run $500–$2,000/year for a single employee',
        'Separate tax return: An S-Corp files Form 1120-S (a corporate return) in addition to your personal 1040. Preparation fees for 1120-S typically run $800–$2,500/year more than a Schedule C return',
        'State registration and compliance: Pennsylvania requires S-Corps to maintain registration and file annual reports',
        'Additional accounting complexity: More accounts, more reconciliation, more bookkeeping requirements',
      ]},
      { type: 'callout', text: 'Total additional annual cost for a typical S-Corp: $2,000–$5,000 per year. This is the hurdle your SE tax savings need to clear to make the election worthwhile.' },
      { type: 'h2', text: 'The "Reasonable Salary" Requirement' },
      { type: 'p', text: 'The IRS requires that S-Corp shareholder-employees receive a salary that is "reasonable" for the services they provide. This is not optional and it\'s not a number you can set arbitrarily low. The IRS has successfully challenged S-Corp owners paying themselves very low salaries in order to maximize distribution income.' },
      { type: 'p', text: 'A reasonable salary is generally what you would pay someone else to do your job — benchmarked against industry wage data. For most professionals, this runs $60,000–$120,000 depending on the role and region. The higher your required reasonable salary, the smaller the distribution on which you avoid SE tax, and the smaller the benefit.' },
      { type: 'h2', text: 'The Math: When Does It Make Sense?' },
      { type: 'p', text: 'As a rough guide, the S-Corp election starts generating meaningful net savings when:' },
      { type: 'ul', items: [
        'Your net business income exceeds $80,000–$100,000 per year',
        'There is meaningful income above your required reasonable salary',
        'You are already paying for payroll processing (or it\'s inexpensive in your situation)',
        'Your accountant can prepare the 1120-S at a reasonable incremental cost',
      ]},
      { type: 'p', text: 'Below $80,000 of net income, the additional costs typically exceed the SE tax savings. Between $80,000 and $150,000, it\'s worth calculating carefully. Above $150,000 of consistent net income, the election almost always generates meaningful net savings.' },
      { type: 'h2', text: 'Timing: The March 15 Deadline' },
      { type: 'p', text: 'To elect S-Corp status for the current tax year, you must file IRS Form 2553 by March 15 of that year (for a calendar-year business). If you miss the deadline, your election generally takes effect in the following tax year — though late elections are sometimes accepted for reasonable cause.' },
      { type: 'p', text: 'If you\'re considering an election for 2027, now (early 2026) is the right time to model the numbers, review your entity structure, and prepare for the transition.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'An S-Corp election is not universally beneficial — it\'s a tool that works well in specific circumstances. Before making the election, model the actual numbers with your accountant: what reasonable salary is required, what the distribution would be, what the SE tax savings would be, and what the incremental compliance costs would run. In many cases the savings are real and substantial. In others, the math doesn\'t work in your favor until the business grows further.' },
    ],
  },
  {
    id: 8,
    category: 'Tax Strategy',
    title: 'Year-End Close Checklist: 12 Things to Do Before December 31',
    excerpt: 'The decisions you make in the last 60 days of the year have an outsized impact on your tax bill. Here\'s the year-end playbook we walk every client through.',
    readTime: '5 min read',
    date: 'January 30, 2026',
    featured: false,
    href: 'article.html?id=8',
    body: [
      { type: 'p', text: 'Tax planning is most powerful before the year ends. Once December 31 passes, most of your options close. The decisions you make in October, November, and early December have an outsized impact on your tax bill — and most of them take only an afternoon to execute.' },
      { type: 'p', text: 'Here\'s the year-end close checklist we walk every client through each fall.' },
      { type: 'h2', text: '1. Run a Profit Projection for the Full Year' },
      { type: 'p', text: 'Before you can make any year-end decisions, you need a reasonably accurate estimate of your full-year net income. Pull your year-to-date P&L and project the remaining months based on current run rate. This gives you a target: how much deductible spending can you pull forward, and how much income (if any) can you defer?' },
      { type: 'h2', text: '2. Max Out Retirement Contributions' },
      { type: 'p', text: 'For sole proprietors and self-employed individuals with a SEP-IRA, you have until the tax filing deadline (including extensions) to contribute. But Solo 401(k) contributions must have the plan established by December 31 and employee deferrals elected by year-end. Know your plan type and its deadlines.' },
      { type: 'p', text: '2026 Solo 401(k) limit: $70,000 combined employee + employer contributions ($77,500 with catch-up if you\'re 50+).' },
      { type: 'h2', text: '3. Make Any Large Equipment Purchases Before December 31' },
      { type: 'p', text: 'Under Section 179 and bonus depreciation rules, equipment placed in service by December 31 can be fully deducted in the current year. "Placed in service" means operational, not just ordered. If you\'ve been considering a major purchase, run the numbers — accelerating it into the current year may make sense depending on your profit projection.' },
      { type: 'h2', text: '4. Review Accounts Receivable' },
      { type: 'p', text: 'If you have outstanding invoices from clients you genuinely cannot collect, a specific write-off before year-end may reduce your taxable income (if you\'re on an accrual basis). On a cash basis, the simpler move is to ensure invoices you expect to collect in January are not accidentally received in December.' },
      { type: 'h2', text: '5. Prepay Deductible Business Expenses' },
      { type: 'p', text: 'Under the IRS "12-month rule," you can prepay certain expenses and deduct them in the current year — including insurance premiums, subscriptions, and some prepaid rent. This is a legitimate income-deferral strategy, but it only makes sense if your current-year tax rate is higher than next year\'s projected rate.' },
      { type: 'h2', text: '6. Review Your Home Office' },
      { type: 'p', text: 'If you work from home and haven\'t been claiming the home office deduction, year-end is a good time to measure your office, document the exclusive use, and ensure you\'re capturing the deduction going forward.' },
      { type: 'h2', text: '7. Consider a Qualified Business Income (QBI) Review' },
      { type: 'p', text: 'Pass-through business owners may be eligible for the 20% QBI deduction. But QBI has income thresholds and limitations that phase in as your income rises. If you\'re approaching the threshold, there may be strategies to keep income within the optimal range — including maximizing retirement contributions.' },
      { type: 'h2', text: '8. Run Payroll for Any S-Corp Compensation Adjustments' },
      { type: 'p', text: 'If you\'re an S-Corp owner and your reasonable compensation wasn\'t set correctly at the start of the year, December is your last opportunity to true it up before the W-2 deadline. Getting this wrong is one of the most common S-Corp compliance errors we see.' },
      { type: 'h2', text: '9. Confirm All Contractor Payments Are Documented' },
      { type: 'p', text: '1099-NEC forms must be issued for any independent contractor paid $600 or more during the year. Collect W-9s now for any contractor you\'ve paid who hasn\'t already provided one — it\'s much easier to get them in December than after the year ends.' },
      { type: 'h2', text: '10. Review Vehicle Usage If You Claim Auto Deductions' },
      { type: 'p', text: 'If you deduct vehicle expenses, your mileage log needs to be current. The IRS standard mileage rate changes annually (check IRS.gov for the 2026 rate). Reconstruct any gaps in your log now while the year is fresh.' },
      { type: 'h2', text: '11. Check for Basis Limitations (S-Corps and Partnerships)' },
      { type: 'p', text: 'Losses from S-Corps and partnerships can only be deducted to the extent of your basis in the entity. If you have pass-through losses you want to utilize this year, confirm your basis allows it before year-end. Adding basis (through contributions or loans in some cases) before December 31 can unlock losses.' },
      { type: 'h2', text: '12. Book a Year-End Planning Call with Your CPA' },
      { type: 'p', text: 'The single most impactful item on this list is the last one. The items above are the starting points — your actual situation may surface additional opportunities or constraints that require judgment. A 30–60 minute planning call in October or November, while you still have time to act, is almost always worth the cost.' },
      { type: 'callout', text: 'November is the ideal time for a year-end planning call. By December, options are narrowing and schedules are full.' },
      { type: 'p', text: 'Year-end planning isn\'t glamorous, but it\'s where real tax savings happen. The strategies that save the most money aren\'t clever loopholes — they\'re ordinary provisions that go unused because no one thought to apply them before the clock ran out.' },
    ],
  },
  {
    id: 9,
    category: 'Tax Strategy',
    title: 'Depletion Deductions for Royalty Interest Owners: What You\'re Probably Leaving on the Table',
    excerpt: 'If you receive oil and gas royalties and aren\'t claiming depletion, you\'re overpaying your taxes. Here\'s how the deduction works and how to calculate it correctly.',
    readTime: '6 min read',
    date: 'May 15, 2026',
    featured: false,
    href: 'article.html?id=9',
    body: [
      { type: 'p', text: 'Western Pennsylvania sits on top of some of the most productive natural gas formations in the country. Thousands of landowners here receive royalty checks from Marcellus and Utica operators — and a surprising number of them are overpaying their taxes because they\'re not claiming the depletion deduction they\'re entitled to.' },
      { type: 'p', text: 'Depletion is a tax deduction that recognizes the gradual exhaustion of a natural resource. Just as a building depreciates over time, the oil and gas reserves beneath your property are a depleting asset. The IRS allows royalty owners to deduct a portion of their royalty income to account for this depletion — and for most royalty interest owners, that deduction is significant.' },
      { type: 'h2', text: 'Two Types of Depletion' },
      { type: 'p', text: 'There are two methods for calculating depletion: cost depletion and percentage depletion. Royalty owners are entitled to use whichever method produces the larger deduction in a given year.' },
      { type: 'p', text: 'Cost depletion is based on what you paid for the mineral rights, spread across the estimated reserves. For landowners who inherited property or have held it for generations, the cost basis may be very low or unknown — which means cost depletion often produces a small deduction or none at all.' },
      { type: 'p', text: 'Percentage depletion is typically far more valuable for royalty interest owners. Under this method, you deduct a fixed percentage of your gross royalty income — regardless of your cost basis. For oil and gas, that percentage is 15%.' },
      { type: 'callout', text: 'A royalty owner receiving $40,000 per year in gas royalties may be entitled to a $6,000 depletion deduction — reducing taxable income before any other adjustments.' },
      { type: 'h2', text: 'The Key Limitation: 100% of Net Income' },
      { type: 'p', text: 'Percentage depletion cannot exceed 100% of the net income from the property. This means if you have high production costs or other deductible items reducing your net royalty income, the deduction may be limited in certain years. In most years for passive royalty owners — who have few expenses to deduct — the 15% figure applies to the full gross royalty amount.' },
      { type: 'h2', text: 'What About Working Interest Owners?' },
      { type: 'p', text: 'Working interest owners — those who share in the costs of drilling and production, not just the royalties — have access to a broader set of deductions including intangible drilling costs (IDCs) and tangible equipment costs. The depletion rules apply to working interests as well, but the overall tax picture is more complex and the deductions are substantially larger. If you hold a working interest, your situation warrants separate analysis.' },
      { type: 'h2', text: 'Where It Goes on Your Return' },
      { type: 'p', text: 'Royalty income is reported on Schedule E of your individual return. The depletion deduction is claimed directly on Schedule E as well, reducing your net royalty income before it flows to your Form 1040. Your 1099 from the operator reports gross royalties — the depletion calculation is your responsibility, not the operator\'s.' },
      { type: 'h2', text: 'Common Mistakes' },
      { type: 'ul', items: [
        'Failing to claim depletion at all — particularly common among taxpayers who prepare their own returns',
        'Using the wrong rate (15% applies to oil and gas; other minerals have different rates)',
        'Confusing gross royalties with net royalties when applying the percentage',
        'Missing the net income limitation in years with high deductible expenses',
        'Not maintaining records of cost basis for inherited mineral rights (which affects cost depletion calculations)',
      ]},
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'If you receive oil and gas royalties and your tax return doesn\'t show a depletion deduction on Schedule E, there\'s a good chance you\'re leaving money on the table. This is one of the most consistently missed deductions we see for Western PA landowners — and it\'s entirely legitimate. If you\'d like us to review your royalty reporting, we\'re glad to take a look.' },
    ],
  },
  {
    id: 10,
    category: 'Tax Strategy',
    title: '2026 Tax Updates: What Changed and What It Means for Your Business',
    excerpt: 'Several tax provisions shifted for 2026. Here\'s a plain-English summary of the changes most likely to affect small business owners and individuals in Western Pennsylvania.',
    readTime: '5 min read',
    date: 'May 12, 2026',
    featured: false,
    href: 'article.html?id=10',
    body: [
      { type: 'p', text: 'Each year brings adjustments to tax brackets, contribution limits, standard deductions, and various thresholds — most tied to inflation. 2026 is no exception. Here\'s a summary of the changes that are most relevant to our clients.' },
      { type: 'h2', text: 'Standard Deduction Increases' },
      { type: 'p', text: 'The standard deduction increased again for 2026, continuing the trend of inflation-driven adjustments. For single filers, the standard deduction is $15,750. For married filing jointly, it\'s $31,500. Head of household filers have a standard deduction of $23,625. These increases reduce taxable income for the majority of individual taxpayers who do not itemize.' },
      { type: 'h2', text: 'Tax Bracket Thresholds' },
      { type: 'p', text: 'The income thresholds for each federal tax bracket are adjusted annually for inflation. For 2026, the brackets shifted modestly upward, meaning a slightly higher income level is required to enter each rate tier. This effectively provides a small tax reduction for most taxpayers even at flat income levels.' },
      { type: 'callout', text: 'The marginal rates themselves — 10%, 12%, 22%, 24%, 32%, 35%, and 37% — did not change. Only the income thresholds shifted.' },
      { type: 'h2', text: 'Retirement Contribution Limits' },
      { type: 'p', text: '401(k) and 403(b) employee contribution limits increased to $23,500 for 2026. The catch-up contribution limit for participants age 50 and older remains $7,500, bringing the total to $31,000. For SIMPLE IRAs, the limit is $16,500. IRA contribution limits (traditional and Roth) remain $7,000, with a $1,000 catch-up for those 50 and older.' },
      { type: 'p', text: 'For self-employed individuals, the Solo 401(k) overall limit (employee plus employer contributions) increased to $70,000, or $77,500 with catch-up contributions. SEP-IRA contributions are limited to the lesser of 25% of compensation or $70,000.' },
      { type: 'h2', text: 'Social Security Wage Base' },
      { type: 'p', text: 'The Social Security wage base — the maximum earned income subject to the 6.2% Social Security tax — increased to $176,100 for 2026. Income above this threshold is not subject to Social Security tax, though it remains subject to the 1.45% Medicare tax with no cap.' },
      { type: 'h2', text: 'Section 179 and Bonus Depreciation' },
      { type: 'p', text: 'The Section 179 expensing limit increased to $1,220,000 for 2026, with a phase-out beginning at $3,050,000 of qualifying property placed in service during the year. Bonus depreciation continues to phase down under current law — it is 40% for 2026 for most property. This makes Section 179 planning more important than in prior years when bonus depreciation was 100%.' },
      { type: 'h2', text: 'Pennsylvania-Specific: Flat Rate Remains Unchanged' },
      { type: 'p', text: 'Pennsylvania\'s individual income tax rate remains 3.07% for 2026, unchanged from prior years. The PA standard deduction does not apply — Pennsylvania taxes most income without a standard deduction equivalent, which is why federal itemized deductions do not carry over to the PA return in the same way.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'The 2026 adjustments are largely inflationary — bracket creep relief and higher contribution limits. The most actionable items for most clients are maximizing retirement contributions at the new limits and understanding how bonus depreciation\'s continued phase-down affects equipment purchasing decisions. If any of these changes affect your planning, reach out and we\'ll walk through the numbers.' },
    ],
  },
  {
    id: 11,
    category: 'Tax Strategy',
    title: 'The One Big Beautiful Bill: What the 2025 Tax Legislation Means for You',
    excerpt: 'Congress passed sweeping tax legislation in 2025. Here\'s a plain-English summary of the provisions most likely to affect small business owners and individual taxpayers.',
    readTime: '7 min read',
    date: 'May 10, 2026',
    featured: false,
    href: 'article.html?id=11',
    body: [
      { type: 'p', text: 'In 2025, Congress passed significant tax legislation that extended, modified, and in some cases made permanent several provisions that were set to expire under the Tax Cuts and Jobs Act of 2017. The legislation touches individual rates, business deductions, estate taxes, and more. Here\'s what matters most for small business owners and individual taxpayers in Western Pennsylvania.' },
      { type: 'h2', text: 'Individual Tax Rates Extended' },
      { type: 'p', text: 'The individual income tax rates established by the 2017 TCJA — including the lower top rate of 37% and the expanded 22% and 24% brackets — were made permanent under the new legislation. Without action, these rates were scheduled to revert to pre-2017 levels (including a top rate of 39.6%) after 2025. That reversion no longer happens.' },
      { type: 'callout', text: 'For most small business owners, keeping the current rates in place is the single largest financial benefit in the legislation.' },
      { type: 'h2', text: 'Standard Deduction Made Permanent — and Increased' },
      { type: 'p', text: 'The roughly doubled standard deduction from 2017 was made permanent and increased further. The higher standard deduction reduces the number of taxpayers for whom itemizing makes sense — a trade-off that simplifies filing for many households but limits the value of certain deductions like mortgage interest and charitable contributions for those who no longer clear the threshold.' },
      { type: 'h2', text: 'Qualified Business Income (QBI) Deduction Extended' },
      { type: 'p', text: 'The 20% deduction for qualified business income — available to pass-through entities including sole proprietors, partnerships, and S-Corps — was extended and made permanent. This deduction reduces the effective tax rate on pass-through business income significantly for owners whose income falls within the eligible thresholds.' },
      { type: 'p', text: 'The income limitations and specified service trade or business restrictions remain in place. If your taxable income exceeds the phase-out threshold ($383,900 for joint filers in 2026), the deduction may be limited or unavailable depending on your industry.' },
      { type: 'h2', text: 'Bonus Depreciation Restored to 100%' },
      { type: 'p', text: 'One of the more significant provisions for business owners: bonus depreciation was restored to 100% for qualifying property placed in service after January 19, 2025. Under prior law, bonus depreciation had been phasing down — it was 60% in 2024 and was scheduled to continue declining. The restoration to 100% allows businesses to immediately expense qualifying equipment, vehicles, and certain improvements in the year of purchase.' },
      { type: 'callout', text: 'If you purchased equipment in 2025 or plan to in 2026, confirm with your CPA whether it qualifies for 100% bonus depreciation under the new rules.' },
      { type: 'h2', text: 'Estate and Gift Tax Exemption' },
      { type: 'p', text: 'The increased estate and gift tax exemption from 2017 was made permanent. The exemption is approximately $13.9 million per individual for 2026 (adjusted for inflation), meaning most estates will not be subject to federal estate tax. For family-owned businesses and farms, this is meaningful long-term planning relief.' },
      { type: 'h2', text: 'SALT Deduction Cap Increased' },
      { type: 'p', text: 'The $10,000 cap on state and local tax (SALT) deductions for itemizers was increased to $40,000 for taxpayers with income below $500,000. For Western PA taxpayers in higher income ranges who pay significant property and state income taxes, this change may make itemizing more advantageous than it was under the $10,000 cap.' },
      { type: 'h2', text: 'What Didn\'t Change' },
      { type: 'p', text: 'The corporate tax rate remains 21%. The self-employment tax structure is unchanged. Pennsylvania\'s flat 3.07% individual rate is a state matter and was not affected by federal legislation.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'The 2025 legislation largely removes tax uncertainty that had been building for years. Rates are stable, key deductions are permanent, and planning horizons are longer. The most impactful near-term change for most business clients is the restoration of 100% bonus depreciation — if you\'ve been deferring major capital purchases, now is a good time to revisit those decisions with the full depreciation picture in view.' },
    ],
  },
  {
    id: 12,
    category: 'Tax Strategy',
    title: 'Understanding Federal Tax Brackets: How Marginal Rates Actually Work',
    excerpt: 'Most people misunderstand how tax brackets work — and that misunderstanding leads to bad decisions. Here\'s a clear explanation of marginal rates and what they mean for your planning.',
    readTime: '5 min read',
    date: 'May 5, 2026',
    featured: false,
    href: 'article.html?id=12',
    body: [
      { type: 'p', text: 'One of the most persistent misconceptions in personal finance is that earning more money can leave you worse off because it "bumps you into a higher tax bracket." It\'s a reasonable-sounding idea — and it\'s wrong. Understanding how tax brackets actually work is foundational to making good financial decisions.' },
      { type: 'h2', text: 'The Marginal Rate System' },
      { type: 'p', text: 'The United States uses a progressive, marginal tax rate system. This means each bracket\'s rate applies only to the income within that bracket — not to your total income. As your income rises, only the dollars above each threshold are taxed at the higher rate.' },
      { type: 'p', text: 'Think of it like a set of buckets. The first bucket holds income up to a certain threshold and is taxed at 10%. Once that bucket is full, income spills into the next bucket (taxed at 12%), then the next (22%), and so on. Each bucket has its own rate, applied only to what\'s in that bucket.' },
      { type: 'h2', text: '2026 Federal Tax Brackets (Single Filers)' },
      { type: 'ul', items: [
        '10%: taxable income up to $11,925',
        '12%: $11,926 to $48,475',
        '22%: $48,476 to $103,350',
        '24%: $103,351 to $197,300',
        '32%: $197,301 to $250,525',
        '35%: $250,526 to $626,350',
        '37%: above $626,350',
      ]},
      { type: 'callout', text: 'For married filing jointly, each bracket threshold is roughly doubled. A couple with $200,000 of taxable income reaches a maximum marginal rate of 24% — but most of their income is taxed at lower rates.' },
      { type: 'h2', text: 'Marginal Rate vs. Effective Rate' },
      { type: 'p', text: 'Your marginal rate is the rate that applies to your next dollar of income. Your effective rate is the percentage of your total income that actually goes to federal tax — a blended average of all the brackets your income passes through.' },
      { type: 'p', text: 'A single filer with $80,000 of taxable income in 2026 has a marginal rate of 22% — but their effective rate is considerably lower, because the first $11,925 was taxed at 10%, the next $36,550 at 12%, and only the remaining income at 22%. The blended effective rate on $80,000 of taxable income is roughly 17%.' },
      { type: 'h2', text: 'Why This Matters for Business Owners' },
      { type: 'p', text: 'Understanding marginal rates changes how you think about deductions. A $10,000 deduction for a taxpayer in the 24% bracket doesn\'t save $2,400 in taxes — it saves exactly $2,400 in taxes, because that $10,000 of income would have been taxed at 24%. Knowing your marginal rate lets you calculate the after-tax cost of decisions quickly.' },
      { type: 'p', text: 'It also affects retirement planning. Pre-tax contributions to a 401(k) or SEP-IRA reduce your taxable income at your marginal rate. If you\'re in the 22% bracket, a $10,000 contribution saves $2,200 in federal taxes — plus the PA flat rate of 3.07%, for a combined $2,507 savings on a $10,000 contribution.' },
      { type: 'h2', text: 'The Bracket Cliff Myth' },
      { type: 'p', text: 'To put the misconception to rest directly: earning an additional dollar of income that pushes you into the next bracket costs you exactly the marginal rate on that one dollar — not on all of your income. There is no scenario in the federal tax system where earning more money results in lower after-tax income. The brackets are designed to prevent that.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'Your marginal rate is a planning tool, not a penalty. Knowing which bracket you\'re in — and how far you are from the next threshold — helps you make better decisions about timing income, taking deductions, and structuring retirement contributions. If you\'re not sure where you land, that\'s exactly the kind of question a mid-year tax planning conversation can answer.' },
    ],
  },
  {
    id: 13,
    category: 'Tax Strategy',
    title: 'The Basics of Depreciation: How the Tax Code Treats Business Assets',
    excerpt: 'When you buy equipment or property for your business, you generally can\'t deduct the full cost immediately. Here\'s how depreciation works — and why it matters for your tax planning.',
    readTime: '5 min read',
    date: 'April 28, 2026',
    featured: false,
    href: 'article.html?id=13',
    body: [
      { type: 'p', text: 'When a business buys a piece of equipment, a vehicle, or commercial property, the IRS generally does not allow a full deduction in the year of purchase. Instead, the cost is spread over several years through a process called depreciation. Understanding how depreciation works is fundamental to making sound equipment and asset decisions.' },
      { type: 'h2', text: 'What Depreciation Is — and Why It Exists' },
      { type: 'p', text: 'Depreciation is the tax code\'s recognition that long-lived assets lose value over time as they wear out, become obsolete, or are consumed in the production of income. Rather than deducting the full cost of a $50,000 piece of equipment in year one, the IRS requires you to recover that cost over the asset\'s "useful life" — typically defined by a schedule called the Modified Accelerated Cost Recovery System (MACRS).' },
      { type: 'h2', text: 'MACRS: The Standard Framework' },
      { type: 'p', text: 'Under MACRS, assets are assigned to property classes with defined recovery periods. Common examples:' },
      { type: 'ul', items: [
        '5-year property: computers, automobiles, light trucks, certain equipment',
        '7-year property: office furniture, fixtures, most machinery and equipment',
        '15-year property: land improvements, fencing, parking lots',
        '27.5-year property: residential rental real estate',
        '39-year property: commercial real estate (office buildings, retail, warehouses)',
      ]},
      { type: 'p', text: 'Within each recovery period, MACRS applies an accelerated depreciation schedule — meaning larger deductions in the early years of the asset\'s life and smaller deductions later. This is more favorable than straight-line depreciation (equal deductions each year), which is why MACRS is the default method for most business assets.' },
      { type: 'h2', text: 'The Half-Year Convention' },
      { type: 'p', text: 'MACRS uses a "half-year convention" for most personal property, meaning assets are treated as placed in service at the midpoint of the year regardless of when you actually bought them. This affects the first-year deduction amount. There\'s also a "mid-quarter convention" that applies if more than 40% of your assets are placed in service in the fourth quarter — a detail worth knowing if you make large purchases late in the year.' },
      { type: 'callout', text: 'Placed in service means the asset is ready and available for use — not just purchased. A piece of equipment still in the box at year-end may not qualify for a current-year deduction.' },
      { type: 'h2', text: 'Real Property Is Different' },
      { type: 'p', text: 'Residential rental property depreciates over 27.5 years on a straight-line basis. Commercial property depreciates over 39 years. Land itself does not depreciate — only the structure. This distinction matters when you acquire property: the purchase price must be allocated between land and building to determine the depreciable basis.' },
      { type: 'h2', text: 'Depreciation and Cash Flow' },
      { type: 'p', text: 'Depreciation is a non-cash deduction — you\'re not writing a check to the IRS for the amount depreciated. But it reduces your taxable income, which reduces your tax liability. For capital-intensive businesses like contractors, manufacturers, and real estate investors, depreciation can be one of the largest deductions on the return.' },
      { type: 'h2', text: 'The Relationship to Basis' },
      { type: 'p', text: 'As you depreciate an asset, your adjusted basis in that asset decreases. When you eventually sell the asset, your gain is calculated against the adjusted (depreciated) basis, not the original purchase price. This means depreciation taken today can create taxable gain on sale later — a concept known as depreciation recapture, which is taxed at ordinary rates for personal property and a capped rate for real property.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'Depreciation is not optional — you generally must depreciate assets over their MACRS lives whether or not you claim the deduction. Failing to do so reduces your basis without the corresponding tax benefit, which creates problems on sale. Understanding the basics of how depreciation works helps you make better decisions about asset purchases, timing, and planning around Section 179 and bonus depreciation — which are covered separately.' },
    ],
  },
  {
    id: 14,
    category: 'Tax Strategy',
    title: 'Bonus Depreciation and Section 179: How to Deduct Equipment in the Year You Buy It',
    excerpt: 'Two provisions allow businesses to deduct the full cost of qualifying assets in the year of purchase rather than spreading deductions over years. Here\'s how each works and when to use them.',
    readTime: '6 min read',
    date: 'April 20, 2026',
    featured: false,
    href: 'article.html?id=14',
    body: [
      { type: 'p', text: 'Standard depreciation spreads equipment deductions over years. But two provisions in the tax code — Section 179 expensing and bonus depreciation — allow businesses to deduct the full cost of qualifying assets in the year they\'re placed in service. Both are valuable planning tools. They work differently, and understanding the distinction helps you use them correctly.' },
      { type: 'h2', text: 'Section 179: The Basics' },
      { type: 'p', text: 'Section 179 allows a business to elect to expense (immediately deduct) the cost of qualifying property rather than depreciating it over time. For 2026, the maximum Section 179 deduction is $1,220,000. The deduction phases out dollar-for-dollar once qualifying property placed in service during the year exceeds $3,050,000 — so Section 179 is designed primarily for small and mid-sized businesses, not large capital-intensive corporations.' },
      { type: 'ul', items: [
        'Qualifying property includes machinery, equipment, vehicles, computers, and certain improvements to non-residential buildings',
        'The property must be used more than 50% for business purposes',
        'The deduction cannot exceed your net business taxable income — it cannot create a loss',
        'Any Section 179 deduction disallowed due to the income limitation carries forward to future years',
      ]},
      { type: 'h2', text: 'Bonus Depreciation: The Basics' },
      { type: 'p', text: 'Bonus depreciation allows an additional first-year depreciation deduction on qualifying new (and, under current law, used) property. Under legislation passed in 2025, bonus depreciation was restored to 100% for property placed in service after January 19, 2025. This means qualifying assets can be fully expensed in the year of purchase — without the income limitation that applies to Section 179.' },
      { type: 'callout', text: 'Unlike Section 179, bonus depreciation can create or increase a net operating loss (NOL), which can be carried forward to offset future years\' income.' },
      { type: 'h2', text: 'Key Differences Between the Two' },
      { type: 'p', text: 'The practical distinction comes down to two things: the income limitation and the ability to create a loss.' },
      { type: 'p', text: 'Section 179 is limited to your net business income — you cannot use it to generate a tax loss. If your business had a thin year, Section 179 may not be usable in full, though the unused amount carries forward. Bonus depreciation has no such limitation. It can create or deepen a net operating loss, which can be carried forward to offset future profitable years.' },
      { type: 'p', text: 'Section 179 also gives you flexibility — you can choose how much of an asset\'s cost to expense under Section 179 and depreciate the remainder normally. Bonus depreciation applies to an entire asset class unless you elect out.' },
      { type: 'h2', text: 'Vehicles: Special Limitations Apply' },
      { type: 'p', text: 'Passenger automobiles are subject to annual depreciation caps under the luxury auto rules, even with Section 179 or bonus depreciation elections. Heavy SUVs (over 6,000 lbs. GVWR) are subject to a $30,500 Section 179 limit for 2026. Large trucks and vans that exceed the weight threshold may qualify for the full deduction. If vehicle purchases are part of your planning, confirm the weight classification before assuming full expensing applies.' },
      { type: 'h2', text: 'Qualified Improvement Property' },
      { type: 'p', text: 'Improvements made to the interior of non-residential commercial buildings — called Qualified Improvement Property (QIP) — have a 15-year MACRS life and qualify for bonus depreciation. This is valuable for businesses that lease and improve commercial space. Tenant improvements, interior renovations, and certain HVAC and roofing work may qualify.' },
      { type: 'h2', text: 'Pennsylvania Conformity' },
      { type: 'p', text: 'Pennsylvania does not conform to federal bonus depreciation or Section 179 at the same levels. PA has its own depreciation rules, which means your PA taxable income and your federal taxable income will differ if you claim significant bonus depreciation or Section 179 on your federal return. This is a common source of confusion for business owners who see one number on their federal return and a higher taxable income on their PA return.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'Both Section 179 and bonus depreciation are legitimate, valuable tools for reducing current-year tax liability on equipment purchases. With 100% bonus depreciation restored for 2025 and beyond, the case for accelerating major capital purchases is stronger than it has been in recent years. Before making a large purchase purely for tax reasons, run the numbers: a deduction reduces taxes, but it doesn\'t eliminate the underlying cost.' },
    ],
  },
  {
    id: 15,
    category: 'Tax Strategy',
    title: 'Standard Deduction vs. Itemizing: How to Know Which Is Better for You',
    excerpt: 'Most taxpayers take the standard deduction without checking whether itemizing would save them more. Here\'s how to think through the decision and what it actually takes to benefit from itemizing.',
    readTime: '5 min read',
    date: 'April 10, 2026',
    featured: false,
    href: 'article.html?id=15',
    body: [
      { type: 'p', text: 'Every individual taxpayer faces a choice when filing their federal return: take the standard deduction or itemize actual deductible expenses. For most people, the standard deduction wins by default — and they\'re right to take it. But for some taxpayers, particularly those with significant mortgage interest, property taxes, or charitable contributions, itemizing can produce a meaningfully lower tax bill.' },
      { type: 'h2', text: 'What the Standard Deduction Is' },
      { type: 'p', text: 'The standard deduction is a flat dollar amount that reduces your taxable income without any documentation or calculation required. For 2026, it\'s $15,750 for single filers, $31,500 for married filing jointly, and $23,625 for head of household. The standard deduction is adjusted annually for inflation.' },
      { type: 'p', text: 'If your itemizable deductions don\'t exceed these amounts, there\'s no tax benefit to itemizing — you\'d be claiming a smaller deduction than the one available to you automatically.' },
      { type: 'h2', text: 'What Can Be Itemized' },
      { type: 'p', text: 'Itemized deductions are reported on Schedule A of your federal return. The major categories are:' },
      { type: 'ul', items: [
        'State and local taxes (SALT): property taxes and either income or sales taxes, capped at $40,000 for 2026 for taxpayers under the income threshold',
        'Mortgage interest: interest on up to $750,000 of acquisition debt on your primary and secondary residence',
        'Charitable contributions: cash and non-cash donations to qualifying organizations, subject to AGI-based limits',
        'Medical expenses: unreimbursed medical costs exceeding 7.5% of your adjusted gross income',
        'Casualty and theft losses: limited to federally declared disaster areas',
      ]},
      { type: 'callout', text: 'The 2025 legislation increased the SALT cap from $10,000 to $40,000 for taxpayers with income below $500,000. This change makes itemizing more advantageous for homeowners in higher property tax areas.' },
      { type: 'h2', text: 'The Decision: A Simple Test' },
      { type: 'p', text: 'Add up your expected itemized deductions. If the total exceeds your standard deduction, itemizing saves you money. If it doesn\'t, take the standard deduction and move on.' },
      { type: 'p', text: 'For most Western PA households, the calculation looks something like this: property taxes on a typical home might be $5,000 to $8,000. Mortgage interest on a mid-sized loan might be $8,000 to $14,000. Charitable contributions might add $2,000 to $5,000. Combined, a married couple in this range is looking at $15,000 to $27,000 in itemizable deductions — below the $31,500 standard deduction threshold. The standard deduction wins.' },
      { type: 'h2', text: 'Who Actually Benefits from Itemizing' },
      { type: 'p', text: 'Taxpayers most likely to benefit from itemizing share some combination of the following characteristics:' },
      { type: 'ul', items: [
        'Large mortgage on a high-value home with significant annual interest',
        'High property taxes (particularly relevant in certain PA counties)',
        'Substantial charitable giving — often 5% or more of income',
        'Significant unreimbursed medical expenses relative to income',
        'Single filers with lower standard deduction thresholds',
      ]},
      { type: 'h2', text: 'Bunching: A Strategy for Those Near the Threshold' },
      { type: 'p', text: 'If your itemizable deductions are close to the standard deduction threshold, consider "bunching" — concentrating deductible expenses into alternating years. For example, make two years\' worth of charitable contributions in a single year, itemize that year, then take the standard deduction the following year. A donor-advised fund makes this strategy easy to execute: you contribute a lump sum in one year, take the charitable deduction, and distribute to charities over time.' },
      { type: 'h2', text: 'Pennsylvania Does Not Use the Same Framework' },
      { type: 'p', text: 'Pennsylvania has no standard deduction and does not allow most federal itemized deductions. PA taxes income at a flat 3.07% rate with very few deductions permitted. The standard vs. itemize decision is entirely a federal question — it has no equivalent on your PA return.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'The standard deduction is the right choice for most taxpayers, and that\'s not a mistake — it\'s how the system is designed. If you\'re close to the threshold, bunching strategies can help you capture itemized deductions in some years while still benefiting from the standard deduction in others. If you\'re not sure which side of the line you fall on, that\'s a 15-minute conversation worth having before you file.' },
    ],
  },
  {
    id: 16,
    category: 'Cash Flow',
    title: 'Why Your Business Is Profitable but Always Short on Cash',
    excerpt: 'Profit and cash are not the same thing. Many healthy businesses struggle with cash despite strong earnings. Here\'s how to read the gap — and what to do about it.',
    readTime: '5 min read',
    date: 'March 30, 2026',
    featured: false,
    href: 'article.html?id=16',
    body: [
      { type: 'p', text: 'One of the most disorienting experiences in business ownership is watching your profit and loss show a healthy number while your bank account tells a different story. You made money — the books say so. So why does it feel like you\'re always short?' },
      { type: 'p', text: 'The answer is that profit and cash are not the same thing. Understanding the gap between them is one of the most practically useful things a business owner can learn.' },
      { type: 'h2', text: 'Profit Is an Accounting Concept. Cash Is Real.' },
      { type: 'p', text: 'Your profit and loss statement is built on accrual accounting — income is recorded when it\'s earned, expenses when they\'re incurred, regardless of when money actually changes hands. If you invoice a client $20,000 in December and they pay in February, that revenue appears in your December P&L. Your December profit looks great. Your December bank account didn\'t receive a dollar.' },
      { type: 'p', text: 'Cash flow, by contrast, reflects actual movement of money in and out of the business. The statement of cash flows is the financial report that tracks this — and it\'s the one most business owners rarely look at.' },
      { type: 'h2', text: 'The Most Common Causes of the Gap' },
      { type: 'ul', items: [
        'Accounts receivable: revenue earned but not yet collected. The larger your AR balance, the more profit is sitting uncollected.',
        'Inventory: goods purchased and sitting unsold. Cash went out; no revenue came in yet.',
        'Loan repayments: principal payments reduce cash but don\'t appear as expenses on the P&L.',
        'Capital expenditures: buying equipment depletes cash but shows up as depreciation over years, not as a current expense.',
        'Owner draws or distributions: money taken out of the business doesn\'t reduce profit but absolutely reduces cash.',
        'Seasonal patterns: revenue concentrated in certain months while expenses run steadily all year.',
      ]},
      { type: 'h2', text: 'The Receivables Problem' },
      { type: 'p', text: 'For service businesses and contractors, slow receivables are typically the primary culprit. A contractor who completes $150,000 of work in Q3 but collects it across Q4 and Q1 of the following year is profitable on paper but cash-poor when it matters. Tightening payment terms, invoicing promptly, and following up on aging receivables directly improves cash flow without changing a single line of your P&L.' },
      { type: 'callout', text: 'If your average collection period is 60 days and you could get it to 30, you\'ve effectively unlocked one month of revenue as available cash — without selling a dollar more.' },
      { type: 'h2', text: 'A Simple Cash Flow Projection' },
      { type: 'p', text: 'The most useful tool for managing cash is a simple 13-week cash flow projection: a spreadsheet listing expected cash in (customer payments, not invoices) and expected cash out (actual vendor payments, payroll, loan payments, owner draws) week by week for the next quarter. This forward view tells you where the gaps are before they become crises.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'A profitable business with cash flow problems is not a contradiction — it\'s a common situation with identifiable causes and real solutions. If you\'re consistently finding yourself short despite strong earnings, start by looking at your receivables aging and your actual cash movements over the past 90 days. The gap is there. Finding it is the first step to closing it.' },
    ],
  },
  {
    id: 17,
    category: 'Business Advisory',
    title: 'When to Move from a Sole Proprietorship to a Formal Entity',
    excerpt: 'Operating as a sole proprietor works at the start. At some point, the risks and inefficiencies outweigh the simplicity. Here\'s how to know when it\'s time to make the move.',
    readTime: '5 min read',
    date: 'March 15, 2026',
    featured: false,
    href: 'article.html?id=17',
    body: [
      { type: 'p', text: 'Most businesses start as sole proprietorships by default. You start doing work, you get paid, you file a Schedule C. It\'s simple, and at the beginning, simple is often right. But as a business grows, the sole proprietorship structure starts creating real risks and inefficiencies that a formal entity — an LLC, S-Corp, or C-Corp — can address.' },
      { type: 'p', text: 'The question isn\'t whether to eventually make the move. It\'s when, and to what.' },
      { type: 'h2', text: 'The Liability Problem' },
      { type: 'p', text: 'A sole proprietor has no legal separation between themselves and their business. Your business debts are your personal debts. If a client sues your business, they\'re suing you. Your personal assets — your home, your savings, your vehicles — are exposed.' },
      { type: 'p', text: 'An LLC (limited liability company) creates a legal boundary between you and the business. Done correctly, a creditor of the business cannot reach your personal assets. This protection isn\'t absolute — it can be pierced if you commingle funds, fail to maintain the entity, or personally guarantee obligations — but it\'s a meaningful shield that a sole proprietorship doesn\'t offer at all.' },
      { type: 'callout', text: 'The moment you have employees, significant client contracts, or any meaningful assets in the business, the liability exposure of a sole proprietorship becomes difficult to justify.' },
      { type: 'h2', text: 'The Self-Employment Tax Problem' },
      { type: 'p', text: 'Sole proprietors pay self-employment tax (15.3% on the first $176,100 of net income, 2.9% above that) on all net profit. As income grows, this becomes a significant cost. An S-Corp structure, by allowing the owner to pay a reasonable salary and take the remaining profit as distributions not subject to SE tax, can reduce this burden once income reaches a level where the compliance costs are justified.' },
      { type: 'h2', text: 'Signals It\'s Time to Make the Move' },
      { type: 'ul', items: [
        'Net profit consistently above $50,000 to $75,000 (SE tax savings begin to matter)',
        'Client contracts that require you to carry significant insurance or indemnify the client',
        'Hiring employees or engaging subcontractors regularly',
        'Taking on business debt — equipment loans, lines of credit',
        'A client or partner requiring you to operate as an entity (not uncommon in B2B services)',
        'Plans to bring in a business partner or investor',
      ]},
      { type: 'h2', text: 'LLC vs. S-Corp vs. C-Corp' },
      { type: 'p', text: 'For most small businesses in this range, the decision is between an LLC (for simplicity and liability protection) and an LLC taxed as an S-Corp (for SE tax savings on top of liability protection). A single-member LLC with no S-Corp election is taxed identically to a sole proprietorship — the liability protection comes without any change to your tax return structure.' },
      { type: 'p', text: 'A C-Corp makes sense in specific situations: businesses pursuing venture capital, companies with complex equity arrangements, or businesses where retained earnings and a flat 21% corporate rate create planning opportunities. For most solo and small business owners in Western PA, it\'s not the right starting point.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'The sole proprietorship is a reasonable starting point, not a permanent structure. If your business is generating meaningful income and you haven\'t formalized your entity, a short planning conversation — covering liability exposure, SE tax math, and the actual cost of formation — will tell you exactly where you stand and whether a change makes sense now.' },
    ],
  },
  {
    id: 18,
    category: 'Bookkeeping',
    title: 'The Chart of Accounts Every Small Business Should Start With',
    excerpt: 'A well-structured chart of accounts is the foundation of useful financial reporting. Here\'s what it should include — and the common mistakes that make books hard to read.',
    readTime: '4 min read',
    date: 'February 28, 2026',
    featured: false,
    href: 'article.html?id=18',
    body: [
      { type: 'p', text: 'The chart of accounts is the organizational backbone of your bookkeeping system — a categorized list of every account used to record financial transactions. Get it right and your financials are clear, your tax prep is straightforward, and your monthly reports actually tell you something. Get it wrong and you spend hours every year trying to find things, re-categorize transactions, and explain to your accountant why "miscellaneous" has $40,000 in it.' },
      { type: 'h2', text: 'The Five Account Types' },
      { type: 'p', text: 'Every account in your chart falls into one of five categories:' },
      { type: 'ul', items: [
        'Assets: what the business owns — checking, savings, accounts receivable, equipment, vehicles',
        'Liabilities: what the business owes — credit cards, loans, accounts payable, sales tax payable',
        'Equity: the owner\'s interest in the business — owner\'s equity, retained earnings, owner\'s draw',
        'Income: revenue from business operations — broken down by service or product line as appropriate',
        'Expenses: costs of running the business — the largest and most detailed category',
      ]},
      { type: 'h2', text: 'How Detailed Is Too Detailed?' },
      { type: 'p', text: 'There\'s a balance to strike. Too few accounts and you can\'t see where your money is going — everything lumped into "expenses" tells you nothing. Too many accounts and your P&L becomes a wall of line items that\'s impossible to read at a glance.' },
      { type: 'p', text: 'A useful rule: you should be able to look at your P&L and immediately understand the shape of your business. If a line item is too small to matter (under 1–2% of revenue), consider consolidating it. If a line item is so large it hides important detail, break it out.' },
      { type: 'h2', text: 'A Starting Framework for Service Businesses' },
      { type: 'ul', items: [
        'Income: Service Revenue (break out by major service line if relevant)',
        'Cost of Services: subcontractors, direct labor, job-specific materials',
        'Operating Expenses: advertising, bank charges, dues and subscriptions, insurance, meals, office supplies, professional fees, rent, repairs and maintenance, software, telephone, travel, utilities, vehicle expenses',
        'Owner compensation: separate from other expenses for clarity',
        'Depreciation: as a standalone line, not buried in other categories',
      ]},
      { type: 'callout', text: 'Avoid the catch-all trap. "Miscellaneous" and "Other" accounts are hiding places for unclassified transactions. If an account regularly accumulates charges, it needs its own category.' },
      { type: 'h2', text: 'Aligning with Your Tax Return' },
      { type: 'p', text: 'Your chart of accounts should map cleanly to the expense categories on Schedule C (for sole proprietors) or Form 1120-S (for S-Corps). When your books use the same categories your tax return uses, year-end prep takes hours instead of days. When they don\'t match, every tax season involves a translation exercise.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'Setting up your chart of accounts correctly at the start — or cleaning it up as part of a bookkeeping overhaul — is one of the highest-leverage things you can do for the long-term efficiency of your finances. If your current books feel hard to read or your accountant spends time reorganizing your data each year, your chart of accounts is probably worth a review.' },
    ],
  },
];

window.INSIGHTS_DATA = INSIGHTS_DATA;
