const INSIGHTS_DATA = [
  {
    id: 1,
    category: 'Tax Strategy',
    title: 'Q2 Tax Deadlines Every Western PA Small Business Owner Should Know',
    excerpt: 'Missing estimated tax deadlines costs more than you think. Here\'s a plain-English breakdown of the April–June filing calendar and how to stay ahead of penalties.',
    readTime: '5 min read',
    date: 'May 8, 2026',
    featured: true,
    href: 'article.html?id=1',
    body: [
      { type: 'p', text: 'If you\'re a small business owner in Western Pennsylvania, the second quarter of the year is one of the busiest — and most consequential — periods on the tax calendar. Between April and June, several key deadlines stack up fast, and missing even one can trigger penalties that compound over time.' },
      { type: 'p', text: 'Here\'s a plain-English guide to the Q2 deadlines that matter most, along with the strategies we walk our clients through every spring.' },
      { type: 'h2', text: 'April 15 — Q1 Estimated Tax Payment Due' },
      { type: 'p', text: 'If you\'re a sole proprietor, partner, or S-Corp shareholder expecting to owe more than $1,000 in federal tax for the year, you\'re required to make quarterly estimated payments. The first installment, covering January through March income, is due April 15.' },
      { type: 'p', text: 'The IRS calculates your underpayment penalty based on a daily rate, so late payments accumulate charges immediately. Pennsylvania follows a similar schedule, with Q1 estimated payments also due April 15 for state purposes.' },
      { type: 'callout', text: 'Rule of thumb: if your prior-year tax liability was $1,000 or more, assume you need to make quarterly estimates.' },
      { type: 'h2', text: 'April 15 — Partnership and S-Corp Extended Returns (with October 15 Deadline)' },
      { type: 'p', text: 'Pass-through entities (partnerships and S-Corps) that filed for an automatic six-month extension on March 15 have until September 15 to file. If you\'re operating as a C-Corp on a calendar year and filed for extension, your extended deadline falls on October 15.' },
      { type: 'p', text: 'Extensions of time to file are not extensions of time to pay. If you owe tax, interest and penalties accrue from the original due date regardless of extension status.' },
      { type: 'h2', text: 'June 16 — Q2 Estimated Tax Payment Due' },
      { type: 'p', text: 'The second estimated payment covers April and May income and is due June 16 (the 15th falls on a weekend in 2026). This is often the deadline that trips people up because it comes just two months after Q1, unlike the three-month gaps later in the year.' },
      { type: 'p', text: 'If your business had a strong spring — a big contract, a seasonal spike, a new service line — your Q2 payment may need to be larger than Q1. Underpaying a single quarter is enough to trigger a penalty even if you\'re current on the others.' },
      { type: 'h2', text: 'How to Calculate What You Owe' },
      { type: 'p', text: 'There are two safe-harbor methods the IRS recognizes for estimated payments:' },
      { type: 'ul', items: [
        '100% of last year\'s tax liability (110% if your prior-year AGI exceeded $150,000)',
        '90% of the current year\'s actual tax liability',
      ]},
      { type: 'p', text: 'Most of our clients use the prior-year safe harbor as a baseline and then adjust mid-year once they have a clearer picture of actual income. This approach minimizes surprises without requiring precise in-year projections.' },
      { type: 'h2', text: 'Pennsylvania-Specific Reminders' },
      { type: 'p', text: 'Pennsylvania imposes its own estimated payment requirements. The PA schedule mirrors the federal calendar — Q1 due April 15, Q2 due June 15 — but the state also requires estimated payments if you expect to owe more than $500 in PA tax for the year. The PA rate (3.07% flat) is applied to the same income base as your federal return, but calculating it separately from federal is a step many self-filers miss.' },
      { type: 'h2', text: 'What Happens If You Miss a Deadline' },
      { type: 'p', text: 'The federal underpayment penalty is currently calculated using the federal short-term rate plus 3 percentage points (check IRS.gov for the current rate). Pennsylvania assesses a similar interest charge. The good news: you can catch up. Paying a late installment doesn\'t eliminate the penalty for that quarter, but it stops the interest from continuing to accrue.' },
      { type: 'callout', text: 'If you\'ve already missed a payment, don\'t wait. Pay what you owe now and we can calculate whether an IRS penalty waiver request is worth filing.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'Q2 is a two-deadline quarter — April and June — that catches a lot of business owners off guard. The best defense is a simple quarterly calendar reminder and a rough income projection updated at the start of each quarter. If you\'re not sure whether you\'re on track, reach out before the next due date. A short call now is far less expensive than a penalty notice later.' },
    ],
  },
  {
    id: 2,
    category: 'Bookkeeping',
    title: 'The Reconciliation Habit That Saves Our Clients Hours Every Month',
    excerpt: 'Most business owners reconcile accounts once a year — right before taxes. Here\'s why doing it monthly changes everything, and a simple system to make it stick.',
    readTime: '4 min read',
    date: 'April 22, 2026',
    featured: false,
    href: 'article.html?id=2',
    body: [
      { type: 'p', text: 'Every January, the same thing happens in our office. Clients arrive for tax prep carrying shoeboxes, bank statements from three different institutions, and a mix of apology and anxiety on their faces. They know the books aren\'t clean. They know the cleanup is going to take time — and money.' },
      { type: 'p', text: 'The fix isn\'t complicated. It\'s monthly reconciliation. And it\'s one of the highest-leverage habits any small business owner can build.' },
      { type: 'h2', text: 'What Reconciliation Actually Means' },
      { type: 'p', text: 'Bank reconciliation is the process of comparing your internal financial records — what\'s in your accounting software or ledger — against your bank and credit card statements. The goal is to confirm that every transaction is recorded, categorized correctly, and that the two sets of numbers match.' },
      { type: 'p', text: 'When they don\'t match, you have an error, a missing entry, or a fraud indicator. All three are problems you want to catch now, not eleven months from now.' },
      { type: 'h2', text: 'Why Annual Reconciliation Is So Painful' },
      { type: 'p', text: 'Annual reconciliation feels like doing twelve months of dishes in a single afternoon. Every transaction needs to be revisited. If your bank statements show a $340 charge from a vendor you can\'t remember, you now have to dig through old emails and invoices to figure out what it was. Your memory of what happened in February is fuzzy in December.' },
      { type: 'p', text: 'Errors compound too. A misclassified transaction in Q1 can distort your P&L for the whole year, which distorts your estimated tax calculations, which means you\'re potentially under- or overpaying taxes — all year long — based on bad data.' },
      { type: 'h2', text: 'What Monthly Reconciliation Looks Like in Practice' },
      { type: 'p', text: 'Done monthly, reconciliation is a 30-to-60-minute task for most small businesses. Here\'s the basic process:' },
      { type: 'ul', items: [
        'Download your bank and credit card statements for the month',
        'Open your accounting software (QuickBooks, Xero, Wave, etc.) and navigate to the reconciliation module',
        'Match every statement transaction to a corresponding entry in your books',
        'Flag and research any transactions that don\'t match',
        'When the ending balances agree, mark the reconciliation complete and save the report',
      ]},
      { type: 'p', text: 'That\'s it. The reason it takes so long at year-end is that you\'re doing this 12 times in a row, against a year\'s worth of fuzzy memory.' },
      { type: 'h2', text: 'The System That Makes It Stick' },
      { type: 'p', text: 'Here\'s what we recommend to clients who\'ve struggled to build the habit:' },
      { type: 'ul', items: [
        'Set a recurring calendar reminder for the 5th of each month (after statements close but before too much time passes)',
        'Treat it like a fixed appointment — 45 minutes, no rescheduling',
        'Keep a running "questions" document for transactions you can\'t immediately identify. Email your bookkeeper with that list at the end of the session rather than rabbit-holing in the moment',
        'If you use a credit card for business, reconcile it separately from the bank account',
      ]},
      { type: 'callout', text: 'The clients who reconcile monthly almost never have surprises at tax time. The ones who don\'t almost always do.' },
      { type: 'h2', text: 'When to Hand It Off' },
      { type: 'p', text: 'If you\'re spending more than 90 minutes on monthly reconciliation, or finding frequent errors you can\'t explain, it\'s time to consider bringing in a bookkeeper. The cost of a monthly reconciliation service is almost always less than the time you\'re spending, and far less than the cost of a tax preparer cleaning up 12 months of errors in January.' },
      { type: 'p', text: 'Monthly reconciliation is one of those tasks that feels optional until it isn\'t. Build the habit now, while the books are manageable. It\'s the single highest-impact change most business owners can make to their financial hygiene.' },
    ],
  },
  {
    id: 3,
    category: 'Cash Flow',
    title: 'Cash Flow vs. Profit: Why You Can Be Profitable and Still Run Out of Money',
    excerpt: 'Your P&L says you\'re doing great. Your bank account says otherwise. This is one of the most common surprises we see with growing businesses — and it\'s entirely preventable.',
    readTime: '6 min read',
    date: 'April 10, 2026',
    featured: false,
    href: 'article.html?id=3',
    body: [
      { type: 'p', text: 'One of the most disorienting moments for a growing business owner is watching the bank account drain while the income statement looks healthy. The P&L says you\'re profitable. The bank account says you can\'t make payroll. What\'s going on?' },
      { type: 'p', text: 'This disconnect between profit and cash is not a sign that something is wrong with your business. It\'s a sign that your business is growing — and that you need to understand two different things at once: profitability and cash flow.' },
      { type: 'h2', text: 'Profit Is Not Cash' },
      { type: 'p', text: 'Profit, as reported on your income statement (P&L), is the difference between your revenue and your expenses in a given period. The problem is that your P&L operates on an accrual basis (or at minimum, a recognition basis) — revenue is recorded when earned, not when the cash actually hits your bank account.' },
      { type: 'p', text: 'If you complete a $50,000 project in December but your client pays in February, your December P&L shows a $50,000 revenue event. Your December bank account shows $0 from that project. Profitable month. Cash-starved month. Both are true at the same time.' },
      { type: 'h2', text: 'The Most Common Cash Flow Killers' },
      { type: 'p', text: 'In our experience working with Western PA small businesses, these are the most frequent culprits behind the profit-cash gap:' },
      { type: 'ul', items: [
        'Slow-paying clients: Net-30 or Net-60 payment terms mean you\'re essentially providing an interest-free loan to your customers',
        'Inventory builds: If you purchase inventory or materials before delivering the finished product, cash is consumed before revenue is recognized',
        'Loan principal payments: Loan payments appear as balance sheet events, not expenses — they reduce your cash but don\'t show up as costs on your P&L',
        'Tax payments: Quarterly estimated tax payments are a cash outflow, but they don\'t reduce reported profit in the period you pay them',
        'Capital expenditures: Buying equipment or making improvements reduces your bank account immediately but is only expensed (depreciated) over years on the P&L',
      ]},
      { type: 'h2', text: 'The Three Financial Statements and Why All Three Matter' },
      { type: 'p', text: 'Most business owners focus exclusively on the P&L. Lenders focus mostly on the balance sheet. But the cash flow statement is often the most important of the three for day-to-day operational decision-making.' },
      { type: 'p', text: 'The cash flow statement reconciles profit to actual cash position by accounting for the timing differences described above. It shows:' },
      { type: 'ul', items: [
        'Operating cash flow: Cash generated by the core business, adjusted for working capital changes',
        'Investing cash flow: Cash used to purchase or sell assets',
        'Financing cash flow: Cash from debt or equity transactions, including loan payments',
      ]},
      { type: 'p', text: 'A business can show strong operating cash flow while being negative overall due to heavy capital investment — that\'s often a healthy growth signal. Or it can show positive investing cash flow (selling assets) while bleeding from operations — a danger sign. The P&L alone can\'t tell you any of that.' },
      { type: 'h2', text: 'Cash Flow Forecasting: The Practical Fix' },
      { type: 'p', text: 'The most powerful tool for managing the profit-cash gap is a rolling cash flow forecast. It doesn\'t need to be complicated:' },
      { type: 'ul', items: [
        'List expected cash inflows by week for the next 8–12 weeks (based on when invoices are actually likely to be paid)',
        'List expected cash outflows by week (payroll, rent, vendor payments, loan payments, taxes)',
        'Track the running cash balance week by week',
      ]},
      { type: 'p', text: 'This simple model will surface cash gaps weeks before they become crises, giving you time to accelerate collections, delay discretionary spending, or draw on a line of credit before you\'re in an emergency.' },
      { type: 'callout', text: 'The goal of a cash flow forecast is not to be perfectly accurate — it\'s to eliminate surprises. Even a rough forecast is vastly better than no forecast.' },
      { type: 'h2', text: 'Quick Wins for Improving Cash Flow' },
      { type: 'ul', items: [
        'Shorten your invoice payment terms from Net-30 to Net-15 or Net-10 (or require deposits on larger projects)',
        'Send invoices immediately upon project completion, not at the end of the month',
        'Offer a small early-payment discount (e.g., 1% if paid within 10 days)',
        'Review subscription and vendor payment dates — cluster them to improve predictability',
        'Establish a business line of credit before you need it (banks are reluctant to lend to businesses in crisis)',
      ]},
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'Profitable businesses fail due to cash flow problems more often than most people realize. Understanding the difference between profit and cash — and actively managing both — is one of the most important financial skills a business owner can develop. If your books are clean and up to date, your accountant can run a cash flow report in minutes. If they\'re not, that\'s the first problem to solve.' },
    ],
  },
  {
    id: 4,
    category: 'Tax Strategy',
    title: 'Home Office Deduction: Who Qualifies and What You Can Actually Claim',
    excerpt: 'Remote workers and home-based business owners in Pennsylvania leave money on the table every year. We break down the IRS rules, the two calculation methods, and common mistakes to avoid.',
    readTime: '7 min read',
    date: 'March 28, 2026',
    featured: false,
    href: 'article.html?id=4',
    body: [
      { type: 'p', text: 'The home office deduction is one of the most misunderstood tax benefits available to self-employed individuals and small business owners. Some people claim it aggressively and get away with it. Others who clearly qualify are afraid to claim it at all. The truth, as usual, is in the details.' },
      { type: 'h2', text: 'The Two Requirements' },
      { type: 'p', text: 'To qualify for the home office deduction, the IRS requires that your workspace meet two tests:' },
      { type: 'ul', items: [
        'Regular and exclusive use: The space must be used regularly for business AND for nothing else. A guest bedroom with a desk in it does not qualify. A dedicated room used only for client meetings and bookkeeping does.',
        'Principal place of business: The home office must be your primary place of business, OR a place where you regularly meet clients or customers.',
      ]},
      { type: 'p', text: 'The "exclusive use" requirement is where most deductions get challenged. If your home office doubles as a playroom, a media room, or a general work-from-home space for your day job, the deduction is on shaky ground.' },
      { type: 'h2', text: 'Who Qualifies (and Who Doesn\'t)' },
      { type: 'callout', text: 'Important: W-2 employees cannot claim the home office deduction under current tax law, regardless of how much they work from home. The Tax Cuts and Jobs Act eliminated miscellaneous itemized deductions — including employee business expenses — through 2025. This provision was extended through 2028 under the 2025 reconciliation legislation.' },
      { type: 'p', text: 'If you are self-employed (sole proprietor, single-member LLC, or partner in a partnership), you may deduct home office expenses on Schedule C or Schedule E. If you\'re an S-Corp shareholder-employee, the deduction works differently — the S-Corp typically reimburses you under an accountable plan, which avoids the self-employment tax complications.' },
      { type: 'h2', text: 'The Two Calculation Methods' },
      { type: 'p', text: 'The IRS offers two methods for calculating the deduction:' },
      { type: 'h2', text: '1. The Simplified Method' },
      { type: 'p', text: 'Multiply the square footage of your home office (up to 300 sq ft) by $5. Maximum deduction: $1,500.' },
      { type: 'p', text: 'This method is easy to calculate and requires minimal recordkeeping. It\'s ideal if your actual home expenses are low or your office is small.' },
      { type: 'h2', text: '2. The Regular Method' },
      { type: 'p', text: 'Determine the percentage of your home used for business (home office square footage ÷ total home square footage). Then apply that percentage to your allowable home expenses:' },
      { type: 'ul', items: [
        'Mortgage interest or rent',
        'Homeowner\'s or renter\'s insurance',
        'Utilities (electricity, gas, internet)',
        'Home repairs and maintenance (proportional share)',
        'Depreciation (for homeowners)',
      ]},
      { type: 'p', text: 'For most business owners with a dedicated home office of any meaningful size, the regular method produces a larger deduction — sometimes significantly larger. However, it requires recordkeeping and a depreciation calculation, and it creates a recapture issue when you sell the home (the depreciation taken is taxed as ordinary income at that time).' },
      { type: 'h2', text: 'Common Mistakes We See' },
      { type: 'ul', items: [
        'Claiming shared space: Using the "office" for any non-business purpose disqualifies the deduction for that space entirely',
        'Forgetting state deductions: Pennsylvania allows a home office deduction for self-employed individuals in addition to the federal deduction',
        'Skipping the deduction out of fear: A legitimate home office, properly documented, is an ordinary and necessary business expense. Not claiming it is leaving real money behind',
        'Ignoring depreciation recapture: If you use the regular method and later sell your home, the depreciation claimed becomes taxable income. This doesn\'t mean you shouldn\'t take the deduction — it means you should plan for it',
      ]},
      { type: 'h2', text: 'Documentation We Recommend' },
      { type: 'p', text: 'If you claim the home office deduction, keep:' },
      { type: 'ul', items: [
        'A floor plan or diagram showing the office\'s location in the home',
        'Square footage measurements of the office and the total home',
        'Photos of the dedicated workspace',
        'Annual totals of all home expenses (mortgage statements, utility bills, insurance premiums)',
      ]},
      { type: 'p', text: 'The IRS doesn\'t require you to submit these records with your return, but they\'re what you\'ll need if the deduction is ever questioned.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'If you run a business from home and use a dedicated space exclusively for that business, you almost certainly qualify for this deduction. The question is which method to use and how to document it properly. Run both methods with your actual numbers before deciding — the difference can easily be $2,000–$5,000 or more for a home-based business with meaningful expenses.' },
    ],
  },
  {
    id: 5,
    category: 'Business Advisory',
    title: 'When Is the Right Time to Switch from DIY Bookkeeping to a CPA?',
    excerpt: 'Not every business needs a CPA on day one. But waiting too long has real costs. We outline the four signs that tell us a client has outgrown their current setup.',
    readTime: '5 min read',
    date: 'March 14, 2026',
    featured: false,
    href: 'article.html?id=5',
    body: [
      { type: 'p', text: 'There\'s a phase in every small business\'s life when spreadsheets and weekend bookkeeping sessions get the job done. Revenue is manageable, expenses are straightforward, and the tax return is basically a Schedule C that you can put together yourself in a long afternoon.' },
      { type: 'p', text: 'Then something changes. A second employee. A major contract. A line of credit. The books get more complex at the same time your time gets more scarce, and suddenly you\'re not sure whether the numbers you\'re looking at are right — or what to do with them even if they are.' },
      { type: 'p', text: 'Here are the four indicators we see most consistently in clients who\'ve outgrown their DIY setup.' },
      { type: 'h2', text: '1. You Hire Your First (or Second) Employee' },
      { type: 'p', text: 'Payroll is a compliance minefield. Federal withholding, Social Security and Medicare taxes, FUTA, Pennsylvania unemployment contributions, and local earned income tax (where applicable) all have different rates, filing schedules, and deposit requirements. Get it wrong, and you\'re looking at trust fund penalties that the IRS collects personally from business owners and officers — they don\'t accept "I didn\'t know" as a defense.' },
      { type: 'p', text: 'The moment you have a W-2 employee, the complexity of your back-office obligations increases dramatically. This is typically when DIY breaks down first.' },
      { type: 'h2', text: '2. Your Tax Return Involves Multiple Forms or Schedules' },
      { type: 'p', text: 'A sole proprietor with a simple business can file Schedule C with confidence. But once you have an S-Corp (Form 1120-S), a partnership interest (Form 1065 / Schedule K-1), rental income (Schedule E), or significant depreciable assets (Form 4562 and depreciation schedules), the return is materially more complex. An error in one schedule ripples through the others.' },
      { type: 'p', text: 'Software like TurboTax can produce a technically "complete" return in these situations. It cannot identify the strategies that would have reduced your liability, catch the elections you didn\'t know to make, or flag the errors introduced by feeding the wrong numbers into the forms.' },
      { type: 'h2', text: '3. Your Books Are More Than 60 Days Behind' },
      { type: 'p', text: 'If you don\'t know your current profit and loss — right now, within a few weeks of real time — you\'re managing your business blind. Most DIY bookkeeping breaks down not because the owner doesn\'t want to do it, but because the operations of the business legitimately don\'t leave time for it.' },
      { type: 'p', text: 'The cost of perpetually out-of-date books isn\'t just the cleanup fee in January. It\'s every pricing decision made without current margin data. Every vendor negotiation made without knowing your cash position. Every loan conversation made without accurate financial statements.' },
      { type: 'h2', text: '4. You\'re Making Decisions That Have Permanent Tax Consequences' },
      { type: 'p', text: 'Certain business decisions — entity type election, retirement plan selection, major equipment purchases, selling a business or real estate, bringing on a partner — have tax implications that play out over years or decades. Making these decisions without professional guidance isn\'t just risky for the current year\'s return. It can lock you into a suboptimal structure for years.' },
      { type: 'callout', text: 'The most expensive CPA conversations we have are the ones that start with "I already did X, what should I do now?" There\'s only so much we can fix after the fact.' },
      { type: 'h2', text: 'What "Getting a CPA" Actually Means' },
      { type: 'p', text: 'Working with a CPA doesn\'t necessarily mean handing off everything. Many of our clients do their own day-to-day bookkeeping in QuickBooks and engage us for quarterly reviews, tax planning, and preparation. That arrangement captures most of the value of professional oversight without the full cost of outsourced bookkeeping.' },
      { type: 'p', text: 'Others prefer to hand off the books entirely and focus on running the business. Either approach can work — the key is knowing what your books actually say, what they mean, and what you should be doing differently.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'There\'s no universal answer to when the switch should happen. But if you recognize yourself in two or more of the situations above, the cost of doing it wrong is almost certainly higher than the cost of doing it right. A single missed payroll tax deposit, a missed deduction, or a suboptimal entity structure can cost multiples of what a year of professional service would have cost.' },
    ],
  },
  {
    id: 6,
    category: 'Bookkeeping',
    title: 'Understanding the Chart of Accounts: The Foundation of Clean Books',
    excerpt: 'A poorly structured chart of accounts creates years of pain at tax time. Here\'s how we set one up for our clients — and what categories most small businesses overlook entirely.',
    readTime: '6 min read',
    date: 'February 27, 2026',
    featured: false,
    href: 'article.html?id=6',
    body: [
      { type: 'p', text: 'The chart of accounts is the skeleton of your bookkeeping system. Everything your accountant does — reconciliation, reporting, tax prep — depends on it being structured correctly. Set it up well once, and your books practically organize themselves. Set it up poorly, and you spend every year in cleanup mode.' },
      { type: 'p', text: 'Here\'s how we think about chart of accounts structure for the small businesses we serve, and the categories most owners overlook entirely.' },
      { type: 'h2', text: 'What the Chart of Accounts Actually Is' },
      { type: 'p', text: 'Your chart of accounts (COA) is a complete list of every financial category — every account — that your business uses to record transactions. Think of it as the filing system that determines where every dollar gets sorted. When you pay rent, which account does it go to? When a customer pays an invoice, which account receives it? The COA provides the answers.' },
      { type: 'p', text: 'Accounts fall into five master categories:' },
      { type: 'ul', items: [
        'Assets: What your business owns (cash, receivables, equipment, inventory)',
        'Liabilities: What your business owes (loans, credit card balances, unpaid vendor invoices)',
        'Equity: The owner\'s residual interest in the business (retained earnings, owner draws)',
        'Income/Revenue: Money earned from your business activities',
        'Expenses: Money spent to generate that income',
      ]},
      { type: 'h2', text: 'The Most Common Structural Mistakes' },
      { type: 'p', text: 'The #1 mistake we see is an expenses section that\'s either too granular or not granular enough. Too many accounts (a separate line for every possible expense) creates a P&L that\'s impossible to read at a glance. Too few (everything lumped into "General Expense") makes it impossible to identify where money is actually going.' },
      { type: 'p', text: 'A good expense structure for most small businesses looks something like this:' },
      { type: 'ul', items: [
        'Cost of Goods Sold / Cost of Services (direct costs tied to revenue generation)',
        'Payroll & Benefits (wages, payroll taxes, health insurance)',
        'Occupancy (rent, utilities, janitorial)',
        'Professional Fees (accounting, legal, consulting)',
        'Marketing & Advertising',
        'Technology & Software',
        'Insurance',
        'Vehicle & Travel',
        'Meals & Entertainment (kept separate because the deduction is limited to 50%)',
        'Office Supplies & Miscellaneous',
      ]},
      { type: 'h2', text: 'Accounts Most Small Businesses Overlook' },
      { type: 'p', text: 'Beyond the obvious operating expenses, there are several account types that small businesses frequently miss — often with real financial or tax consequences:' },
      { type: 'ul', items: [
        'Owner\'s Draw / Distribution account: If you\'re a sole proprietor or S-Corp shareholder, how you take money out of the business matters. Distributions should be tracked separately from salary and from business expenses',
        'Due to/from Owner: When owners pay business expenses from personal accounts (or vice versa), there should be a clearing account to track these intercompany transactions',
        'Depreciation expense: If you own equipment, vehicles, or property, depreciation is a real expense that should be recorded monthly — not only at tax time',
        'Unearned Revenue / Customer Deposits: If clients pay you before you deliver services, that money is a liability until earned — not income',
        'Sales Tax Payable: If you collect sales tax, it needs a dedicated liability account so you know exactly what you owe the state at any point',
      ]},
      { type: 'h2', text: 'How to Set It Up in QuickBooks or Xero' },
      { type: 'p', text: 'Both QuickBooks Online and Xero create a default chart of accounts during setup. The default is a reasonable starting point, but it should always be reviewed and adjusted for your specific business. Key customizations:' },
      { type: 'ul', items: [
        'Delete accounts you will never use (simplicity matters)',
        'Add sub-accounts where you need more detail (e.g., breaking "Payroll" into "Wages" and "Payroll Taxes")',
        'Map your expense accounts to the IRS Schedule C categories relevant to your business — your software may have a built-in mapping field',
        'Use account numbers to maintain logical ordering (1000s for assets, 2000s for liabilities, 3000s for equity, 4000s for income, 5000s+ for expenses)',
      ]},
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'A few hours invested in setting up your COA correctly saves dozens of hours at year-end. If you\'ve been in business for more than a year and haven\'t reviewed your chart of accounts against your actual expense patterns, now is a good time. We regularly do COA audits as part of our bookkeeping setup service — if your books feel chaotic, this is almost always the root cause.' },
    ],
  },
  {
    id: 7,
    category: 'Business Advisory',
    title: 'S-Corp Election: Is It the Right Move for Your Business in 2026?',
    excerpt: 'S-Corp status can save a profitable business thousands in self-employment taxes — but it comes with real administrative costs. We walk through the math and who it actually makes sense for.',
    readTime: '8 min read',
    date: 'February 12, 2026',
    featured: false,
    href: 'article.html?id=7',
    body: [
      { type: 'p', text: 'Every year, we have dozens of conversations with business owners who\'ve heard that electing S-Corp status will save them significant money in taxes. Sometimes it\'s true. Sometimes the savings are real but smaller than expected. And sometimes the administrative overhead negates most of the benefit.' },
      { type: 'p', text: 'Here\'s a straightforward framework for evaluating whether an S-Corp election makes sense for your business in 2026.' },
      { type: 'h2', text: 'The Tax Advantage in Plain Language' },
      { type: 'p', text: 'By default, a sole proprietor or single-member LLC owner pays self-employment (SE) tax — currently 15.3% — on all net business income, up to the Social Security wage base ($176,100 in 2026) and 2.9% above that.' },
      { type: 'p', text: 'An S-Corp changes the structure. As an S-Corp shareholder-employee, you pay yourself a "reasonable salary." That salary is subject to payroll taxes (FICA), which mirror SE tax at 15.3%. But any remaining profit distributed to you as a shareholder is not subject to SE tax or FICA. That\'s the savings opportunity.' },
      { type: 'p', text: 'Example: If your business nets $200,000 and you elect S-Corp status, paying yourself a $100,000 salary and taking $100,000 in distributions, you pay FICA on the $100,000 salary but avoid SE tax on the $100,000 distribution. SE tax savings on the distribution: roughly $14,130.' },
      { type: 'h2', text: 'The Costs That Offset the Savings' },
      { type: 'p', text: 'An S-Corp election introduces real, recurring costs that a sole proprietorship or single-member LLC does not have:' },
      { type: 'ul', items: [
        'Payroll processing: You must run payroll and pay yourself a W-2 salary. Payroll service costs typically run $500–$2,000/year for a single employee',
        'Separate tax return: An S-Corp files Form 1120-S (a corporate return) in addition to your personal 1040. Preparation fees for 1120-S typically run $800–$2,500/year more than a Schedule C return',
        'State registration and compliance: Pennsylvania requires S-Corps to maintain registration and file annual reports',
        'Additional accounting complexity: More accounts, more reconciliation, more bookkeeping requirements',
      ]},
      { type: 'callout', text: 'Total additional annual cost for a typical S-Corp: $2,000–$5,000 per year. This is the hurdle your SE tax savings need to clear to make the election worthwhile.' },
      { type: 'h2', text: 'The "Reasonable Salary" Requirement' },
      { type: 'p', text: 'The IRS requires that S-Corp shareholder-employees receive a salary that is "reasonable" for the services they provide. This is not optional and it\'s not a number you can set arbitrarily low. The IRS has successfully challenged S-Corp owners paying themselves very low salaries in order to maximize distribution income.' },
      { type: 'p', text: 'A reasonable salary is generally what you would pay someone else to do your job — benchmarked against industry wage data. For most professionals, this runs $60,000–$120,000 depending on the role and region. The higher your required reasonable salary, the smaller the distribution on which you avoid SE tax, and the smaller the benefit.' },
      { type: 'h2', text: 'The Math: When Does It Make Sense?' },
      { type: 'p', text: 'As a rough guide, the S-Corp election starts generating meaningful net savings when:' },
      { type: 'ul', items: [
        'Your net business income exceeds $80,000–$100,000 per year',
        'There is meaningful income above your required reasonable salary',
        'You are already paying for payroll processing (or it\'s inexpensive in your situation)',
        'Your accountant can prepare the 1120-S at a reasonable incremental cost',
      ]},
      { type: 'p', text: 'Below $80,000 of net income, the additional costs typically exceed the SE tax savings. Between $80,000 and $150,000, it\'s worth calculating carefully. Above $150,000 of consistent net income, the election almost always generates meaningful net savings.' },
      { type: 'h2', text: 'Timing: The March 15 Deadline' },
      { type: 'p', text: 'To elect S-Corp status for the current tax year, you must file IRS Form 2553 by March 15 of that year (for a calendar-year business). If you miss the deadline, your election generally takes effect in the following tax year — though late elections are sometimes accepted for reasonable cause.' },
      { type: 'p', text: 'If you\'re considering an election for 2027, now (early 2026) is the right time to model the numbers, review your entity structure, and prepare for the transition.' },
      { type: 'h2', text: 'The Bottom Line' },
      { type: 'p', text: 'An S-Corp election is not universally beneficial — it\'s a tool that works well in specific circumstances. Before making the election, model the actual numbers with your accountant: what reasonable salary is required, what the distribution would be, what the SE tax savings would be, and what the incremental compliance costs would run. In many cases the savings are real and substantial. In others, the math doesn\'t work in your favor until the business grows further.' },
    ],
  },
  {
    id: 8,
    category: 'Tax Strategy',
    title: 'Year-End Close Checklist: 12 Things to Do Before December 31',
    excerpt: 'The decisions you make in the last 60 days of the year have an outsized impact on your tax bill. Here\'s the year-end playbook we walk every client through.',
    readTime: '5 min read',
    date: 'January 30, 2026',
    featured: false,
    href: 'article.html?id=8',
    body: [
      { type: 'p', text: 'Tax planning is most powerful before the year ends. Once December 31 passes, most of your options close. The decisions you make in October, November, and early December have an outsized impact on your tax bill — and most of them take only an afternoon to execute.' },
      { type: 'p', text: 'Here\'s the year-end close checklist we walk every client through each fall.' },
      { type: 'h2', text: '1. Run a Profit Projection for the Full Year' },
      { type: 'p', text: 'Before you can make any year-end decisions, you need a reasonably accurate estimate of your full-year net income. Pull your year-to-date P&L and project the remaining months based on current run rate. This gives you a target: how much deductible spending can you pull forward, and how much income (if any) can you defer?' },
      { type: 'h2', text: '2. Max Out Retirement Contributions' },
      { type: 'p', text: 'For sole proprietors and self-employed individuals with a SEP-IRA, you have until the tax filing deadline (including extensions) to contribute. But Solo 401(k) contributions must have the plan established by December 31 and employee deferrals elected by year-end. Know your plan type and its deadlines.' },
      { type: 'p', text: '2026 Solo 401(k) limit: $70,000 combined employee + employer contributions ($77,500 with catch-up if you\'re 50+).' },
      { type: 'h2', text: '3. Make Any Large Equipment Purchases Before December 31' },
      { type: 'p', text: 'Under Section 179 and bonus depreciation rules, equipment placed in service by December 31 can be fully deducted in the current year. "Placed in service" means operational, not just ordered. If you\'ve been considering a major purchase, run the numbers — accelerating it into the current year may make sense depending on your profit projection.' },
      { type: 'h2', text: '4. Review Accounts Receivable' },
      { type: 'p', text: 'If you have outstanding invoices from clients you genuinely cannot collect, a specific write-off before year-end may reduce your taxable income (if you\'re on an accrual basis). On a cash basis, the simpler move is to ensure invoices you expect to collect in January are not accidentally received in December.' },
      { type: 'h2', text: '5. Prepay Deductible Business Expenses' },
      { type: 'p', text: 'Under the IRS "12-month rule," you can prepay certain expenses and deduct them in the current year — including insurance premiums, subscriptions, and some prepaid rent. This is a legitimate income-deferral strategy, but it only makes sense if your current-year tax rate is higher than next year\'s projected rate.' },
      { type: 'h2', text: '6. Review Your Home Office' },
      { type: 'p', text: 'If you work from home and haven\'t been claiming the home office deduction, year-end is a good time to measure your office, document the exclusive use, and ensure you\'re capturing the deduction going forward.' },
      { type: 'h2', text: '7. Consider a Qualified Business Income (QBI) Review' },
      { type: 'p', text: 'Pass-through business owners may be eligible for the 20% QBI deduction. But QBI has income thresholds and limitations that phase in as your income rises. If you\'re approaching the threshold, there may be strategies to keep income within the optimal range — including maximizing retirement contributions.' },
      { type: 'h2', text: '8. Run Payroll for Any S-Corp Compensation Adjustments' },
      { type: 'p', text: 'If you\'re an S-Corp owner and your reasonable compensation wasn\'t set correctly at the start of the year, December is your last opportunity to true it up before the W-2 deadline. Getting this wrong is one of the most common S-Corp compliance errors we see.' },
      { type: 'h2', text: '9. Confirm All Contractor Payments Are Documented' },
      { type: 'p', text: '1099-NEC forms must be issued for any independent contractor paid $600 or more during the year. Collect W-9s now for any contractor you\'ve paid who hasn\'t already provided one — it\'s much easier to get them in December than after the year ends.' },
      { type: 'h2', text: '10. Review Vehicle Usage If You Claim Auto Deductions' },
      { type: 'p', text: 'If you deduct vehicle expenses, your mileage log needs to be current. The IRS standard mileage rate changes annually (check IRS.gov for the 2026 rate). Reconstruct any gaps in your log now while the year is fresh.' },
      { type: 'h2', text: '11. Check for Basis Limitations (S-Corps and Partnerships)' },
      { type: 'p', text: 'Losses from S-Corps and partnerships can only be deducted to the extent of your basis in the entity. If you have pass-through losses you want to utilize this year, confirm your basis allows it before year-end. Adding basis (through contributions or loans in some cases) before December 31 can unlock losses.' },
      { type: 'h2', text: '12. Book a Year-End Planning Call with Your CPA' },
      { type: 'p', text: 'The single most impactful item on this list is the last one. The items above are the starting points — your actual situation may surface additional opportunities or constraints that require judgment. A 30–60 minute planning call in October or November, while you still have time to act, is almost always worth the cost.' },
      { type: 'callout', text: 'November is the ideal time for a year-end planning call. By December, options are narrowing and schedules are full.' },
      { type: 'p', text: 'Year-end planning isn\'t glamorous, but it\'s where real tax savings happen. The strategies that save the most money aren\'t clever loopholes — they\'re ordinary provisions that go unused because no one thought to apply them before the clock ran out.' },
    ],
  },
];

window.INSIGHTS_DATA = INSIGHTS_DATA;
